import type {
    PatternConfig,
    PatternPreset,
    PatternPresetCategory,
    PatternType,
} from "./pattern.types";

interface PresetInput {
    id: string;
    name: string;
    patternType: PatternType;
    backgroundColor: string;
    patternColor: string;
    secondaryColor?: string;
    size?: number;
    gapX?: number;
    gapY?: number;
    thickness?: number;
    opacity?: number;
    angle?: number;
    positionX?: number;
    positionY?: number;
    elementOffsetX?: number;
    elementOffsetY?: number;
    scaleX?: number;
    scaleY?: number;
}

const createPreset = ({
    id,
    name,
    patternType,
    backgroundColor,
    patternColor,
    secondaryColor = patternColor,
    size = 32,
    gapX = 0,
    gapY = 0,
    thickness = 2,
    opacity = 70,
    angle = 0,
    positionX = 0,
    positionY = 0,
    elementOffsetX = 0,
    elementOffsetY = 0,
    scaleX = 100,
    scaleY = 100,
}: PresetInput): PatternPreset => {
    const config: PatternConfig = {
        patternType,
        backgroundColor,
        patternColor,
        secondaryColor,
        size,
        gapX,
        gapY,
        thickness,
        opacity,
        angle,
        positionX,
        positionY,
        elementOffsetX,
        elementOffsetY,
        scaleX,
        scaleY,
    };

    return {
        id,
        name,
        config,
    };
};

const createPresets = (presets: PresetInput[]): PatternPreset[] => {
    return presets.map(createPreset);
};

const honeycombPresets = createPresets([
    {
        id: "honeycomb-golden",
        name: "Golden Hive",
        patternType: "honeycomb",
        backgroundColor: "#1c1205",
        patternColor: "#f59e0b",
        secondaryColor: "#fbbf24",
        size: 22,
        opacity: 78,
    },
    {
        id: "honeycomb-amber",
        name: "Amber Hive",
        patternType: "honeycomb",
        backgroundColor: "#2a1705",
        patternColor: "#d97706",
        secondaryColor: "#f59e0b",
        size: 28,
        opacity: 70,
    },
    {
        id: "honeycomb-honey",
        name: "Pure Honey",
        patternType: "honeycomb",
        backgroundColor: "#422006",
        patternColor: "#facc15",
        secondaryColor: "#fde047",
        size: 34,
        opacity: 65,
    },
    {
        id: "honeycomb-black",
        name: "Black Hive",
        patternType: "honeycomb",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        secondaryColor: "#27272a",
        size: 24,
        opacity: 72,
    },
    {
        id: "honeycomb-carbon",
        name: "Carbon Hive",
        patternType: "honeycomb",
        backgroundColor: "#18181b",
        patternColor: "#71717a",
        secondaryColor: "#3f3f46",
        size: 18,
        opacity: 55,
    },
    {
        id: "honeycomb-emerald",
        name: "Emerald Hive",
        patternType: "honeycomb",
        backgroundColor: "#022c22",
        patternColor: "#10b981",
        secondaryColor: "#6ee7b7",
        size: 26,
        opacity: 62,
    },
    {
        id: "honeycomb-teal",
        name: "Teal Hive",
        patternType: "honeycomb",
        backgroundColor: "#042f2e",
        patternColor: "#14b8a6",
        secondaryColor: "#5eead4",
        size: 30,
        opacity: 60,
    },
    {
        id: "honeycomb-cyan",
        name: "Cyan Hive",
        patternType: "honeycomb",
        backgroundColor: "#083344",
        patternColor: "#22d3ee",
        secondaryColor: "#67e8f9",
        size: 22,
        opacity: 64,
    },
    {
        id: "honeycomb-blue",
        name: "Blue Hive",
        patternType: "honeycomb",
        backgroundColor: "#172554",
        patternColor: "#3b82f6",
        secondaryColor: "#93c5fd",
        size: 30,
        opacity: 58,
    },
    {
        id: "honeycomb-violet",
        name: "Violet Hive",
        patternType: "honeycomb",
        backgroundColor: "#2e1065",
        patternColor: "#8b5cf6",
        secondaryColor: "#c4b5fd",
        size: 26,
        opacity: 65,
    },
    {
        id: "honeycomb-magenta",
        name: "Magenta Hive",
        patternType: "honeycomb",
        backgroundColor: "#4a044e",
        patternColor: "#d946ef",
        secondaryColor: "#f0abfc",
        size: 28,
        opacity: 62,
    },
    {
        id: "honeycomb-rose",
        name: "Rose Hive",
        patternType: "honeycomb",
        backgroundColor: "#4c0519",
        patternColor: "#f43f5e",
        secondaryColor: "#fda4af",
        size: 24,
        opacity: 60,
    },
    {
        id: "honeycomb-ice",
        name: "Ice Hive",
        patternType: "honeycomb",
        backgroundColor: "#e0f2fe",
        patternColor: "#38bdf8",
        secondaryColor: "#7dd3fc",
        size: 28,
        opacity: 40,
    },
    {
        id: "honeycomb-paper",
        name: "Paper Hive",
        patternType: "honeycomb",
        backgroundColor: "#ffffff",
        patternColor: "#94a3b8",
        secondaryColor: "#cbd5e1",
        size: 30,
        opacity: 28,
    },
]);

const diamondsPresets = createPresets([
    {
        id: "diamonds-amethyst",
        name: "Amethyst",
        patternType: "diamonds",
        backgroundColor: "#1e1b4b",
        patternColor: "#8b5cf6",
        secondaryColor: "#c4b5fd",
        size: 42,
        opacity: 62,
    },
    {
        id: "diamonds-emerald",
        name: "Emerald",
        patternType: "diamonds",
        backgroundColor: "#022c22",
        patternColor: "#10b981",
        secondaryColor: "#6ee7b7",
        size: 44,
        opacity: 58,
    },
    {
        id: "diamonds-sapphire",
        name: "Sapphire",
        patternType: "diamonds",
        backgroundColor: "#172554",
        patternColor: "#3b82f6",
        secondaryColor: "#60a5fa",
        size: 46,
        opacity: 62,
    },
    {
        id: "diamonds-ruby",
        name: "Ruby",
        patternType: "diamonds",
        backgroundColor: "#450a0a",
        patternColor: "#ef4444",
        secondaryColor: "#fca5a5",
        size: 44,
        opacity: 60,
    },
    {
        id: "diamonds-rose",
        name: "Rose Crystal",
        patternType: "diamonds",
        backgroundColor: "#500724",
        patternColor: "#ec4899",
        secondaryColor: "#f9a8d4",
        size: 40,
        opacity: 60,
    },
    {
        id: "diamonds-cyan",
        name: "Cyan Crystal",
        patternType: "diamonds",
        backgroundColor: "#083344",
        patternColor: "#06b6d4",
        secondaryColor: "#67e8f9",
        size: 40,
        opacity: 60,
    },
    {
        id: "diamonds-gold",
        name: "Gold",
        patternType: "diamonds",
        backgroundColor: "#2d1b05",
        patternColor: "#f59e0b",
        secondaryColor: "#fde047",
        size: 48,
        opacity: 62,
    },
    {
        id: "diamonds-obsidian",
        name: "Obsidian",
        patternType: "diamonds",
        backgroundColor: "#000000",
        patternColor: "#27272a",
        secondaryColor: "#52525b",
        size: 46,
        opacity: 72,
    },
    {
        id: "diamonds-steel",
        name: "Steel",
        patternType: "diamonds",
        backgroundColor: "#18181b",
        patternColor: "#71717a",
        secondaryColor: "#a1a1aa",
        size: 36,
        opacity: 50,
    },
    {
        id: "diamonds-lavender",
        name: "Lavender",
        patternType: "diamonds",
        backgroundColor: "#f5f3ff",
        patternColor: "#a78bfa",
        secondaryColor: "#ddd6fe",
        size: 42,
        opacity: 42,
    },
    {
        id: "diamonds-mint",
        name: "Mint",
        patternType: "diamonds",
        backgroundColor: "#ecfdf5",
        patternColor: "#34d399",
        secondaryColor: "#a7f3d0",
        size: 44,
        opacity: 38,
    },
    {
        id: "diamonds-monochrome",
        name: "Monochrome",
        patternType: "diamonds",
        backgroundColor: "#fafafa",
        patternColor: "#71717a",
        secondaryColor: "#d4d4d8",
        size: 38,
        opacity: 32,
    },
]);

const wavesPresets = createPresets([
    {
        id: "waves-ocean",
        name: "Ocean",
        patternType: "waves",
        backgroundColor: "#082f49",
        patternColor: "#0ea5e9",
        secondaryColor: "#67e8f9",
        size: 64,
        opacity: 52,
    },
    {
        id: "waves-deep-ocean",
        name: "Deep Ocean",
        patternType: "waves",
        backgroundColor: "#020617",
        patternColor: "#0284c7",
        secondaryColor: "#0e7490",
        size: 72,
        opacity: 55,
    },
    {
        id: "waves-lagoon",
        name: "Lagoon",
        patternType: "waves",
        backgroundColor: "#042f2e",
        patternColor: "#14b8a6",
        secondaryColor: "#99f6e4",
        size: 58,
        opacity: 48,
    },
    {
        id: "waves-seafoam",
        name: "Sea Foam",
        patternType: "waves",
        backgroundColor: "#ecfeff",
        patternColor: "#22d3ee",
        secondaryColor: "#5eead4",
        size: 54,
        opacity: 36,
    },
    {
        id: "waves-violet",
        name: "Violet Tide",
        patternType: "waves",
        backgroundColor: "#2e1065",
        patternColor: "#a855f7",
        secondaryColor: "#e879f9",
        size: 62,
        opacity: 50,
    },
    {
        id: "waves-sunset",
        name: "Sunset",
        patternType: "waves",
        backgroundColor: "#431407",
        patternColor: "#f97316",
        secondaryColor: "#fb7185",
        size: 66,
        opacity: 54,
    },
    {
        id: "waves-flamingo",
        name: "Flamingo",
        patternType: "waves",
        backgroundColor: "#500724",
        patternColor: "#f472b6",
        secondaryColor: "#f9a8d4",
        size: 56,
        opacity: 55,
    },
    {
        id: "waves-midnight",
        name: "Midnight",
        patternType: "waves",
        backgroundColor: "#09090b",
        patternColor: "#3f3f46",
        secondaryColor: "#71717a",
        size: 58,
        opacity: 55,
    },
    {
        id: "waves-electric",
        name: "Electric",
        patternType: "waves",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#8b5cf6",
        size: 52,
        opacity: 62,
    },
    {
        id: "waves-forest",
        name: "Forest",
        patternType: "waves",
        backgroundColor: "#052e16",
        patternColor: "#22c55e",
        secondaryColor: "#84cc16",
        size: 64,
        opacity: 45,
    },
    {
        id: "waves-sand",
        name: "Sand",
        patternType: "waves",
        backgroundColor: "#fffbeb",
        patternColor: "#f59e0b",
        secondaryColor: "#fdba74",
        size: 68,
        opacity: 32,
    },
    {
        id: "waves-ice",
        name: "Ice",
        patternType: "waves",
        backgroundColor: "#f0f9ff",
        patternColor: "#38bdf8",
        secondaryColor: "#a5f3fc",
        size: 60,
        opacity: 34,
    },
]);

const cloudsPresets = createPresets([
    {
        id: "clouds-blue-sky",
        name: "Blue Sky",
        patternType: "clouds",
        backgroundColor: "#bae6fd",
        patternColor: "#ffffff",
        secondaryColor: "#f8fafc",
        size: 58,
        opacity: 82,
    },
    {
        id: "clouds-soft",
        name: "Soft Clouds",
        patternType: "clouds",
        backgroundColor: "#dbeafe",
        patternColor: "#ffffff",
        secondaryColor: "#eff6ff",
        size: 72,
        opacity: 74,
    },
    {
        id: "clouds-lavender",
        name: "Lavender Sky",
        patternType: "clouds",
        backgroundColor: "#ddd6fe",
        patternColor: "#ffffff",
        secondaryColor: "#f5f3ff",
        size: 64,
        opacity: 72,
    },
    {
        id: "clouds-pink",
        name: "Pink Sky",
        patternType: "clouds",
        backgroundColor: "#fbcfe8",
        patternColor: "#ffffff",
        secondaryColor: "#fdf2f8",
        size: 68,
        opacity: 70,
    },
    {
        id: "clouds-sunset",
        name: "Sunset Clouds",
        patternType: "clouds",
        backgroundColor: "#fed7aa",
        patternColor: "#fff7ed",
        secondaryColor: "#fda4af",
        size: 76,
        opacity: 64,
    },
    {
        id: "clouds-night",
        name: "Night Clouds",
        patternType: "clouds",
        backgroundColor: "#172554",
        patternColor: "#64748b",
        secondaryColor: "#94a3b8",
        size: 72,
        opacity: 50,
    },
    {
        id: "clouds-storm",
        name: "Storm",
        patternType: "clouds",
        backgroundColor: "#27272a",
        patternColor: "#52525b",
        secondaryColor: "#71717a",
        size: 62,
        opacity: 60,
    },
    {
        id: "clouds-mint",
        name: "Mint Sky",
        patternType: "clouds",
        backgroundColor: "#ccfbf1",
        patternColor: "#ffffff",
        secondaryColor: "#f0fdfa",
        size: 66,
        opacity: 68,
    },
    {
        id: "clouds-violet-night",
        name: "Violet Night",
        patternType: "clouds",
        backgroundColor: "#2e1065",
        patternColor: "#7c3aed",
        secondaryColor: "#a78bfa",
        size: 70,
        opacity: 52,
    },
    {
        id: "clouds-peach",
        name: "Peach Sky",
        patternType: "clouds",
        backgroundColor: "#ffedd5",
        patternColor: "#ffffff",
        secondaryColor: "#fef3c7",
        size: 60,
        opacity: 72,
    },
    {
        id: "clouds-gray",
        name: "Overcast",
        patternType: "clouds",
        backgroundColor: "#cbd5e1",
        patternColor: "#f8fafc",
        secondaryColor: "#e2e8f0",
        size: 64,
        opacity: 72,
    },
    {
        id: "clouds-dark",
        name: "Dark Clouds",
        patternType: "clouds",
        backgroundColor: "#020617",
        patternColor: "#334155",
        secondaryColor: "#475569",
        size: 78,
        opacity: 58,
    },
]);

const bubblesPresets = createPresets([
    {
        id: "bubbles-aqua",
        name: "Aqua Bubbles",
        patternType: "bubbles",
        backgroundColor: "#083344",
        patternColor: "#22d3ee",
        secondaryColor: "#67e8f9",
        size: 34,
        thickness: 2,
        opacity: 65,
    },
    {
        id: "bubbles-ocean",
        name: "Ocean Bubbles",
        patternType: "bubbles",
        backgroundColor: "#082f49",
        patternColor: "#38bdf8",
        secondaryColor: "#7dd3fc",
        size: 40,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "bubbles-pink",
        name: "Pink Bubbles",
        patternType: "bubbles",
        backgroundColor: "#500724",
        patternColor: "#f472b6",
        secondaryColor: "#f9a8d4",
        size: 38,
        thickness: 2,
        opacity: 60,
    },
    {
        id: "bubbles-candy",
        name: "Candy Bubbles",
        patternType: "bubbles",
        backgroundColor: "#fdf2f8",
        patternColor: "#ec4899",
        secondaryColor: "#8b5cf6",
        size: 36,
        thickness: 2,
        opacity: 45,
    },
    {
        id: "bubbles-violet",
        name: "Violet Bubbles",
        patternType: "bubbles",
        backgroundColor: "#2e1065",
        patternColor: "#a78bfa",
        secondaryColor: "#e879f9",
        size: 42,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "bubbles-mint",
        name: "Mint Bubbles",
        patternType: "bubbles",
        backgroundColor: "#ecfdf5",
        patternColor: "#10b981",
        secondaryColor: "#5eead4",
        size: 34,
        thickness: 2,
        opacity: 42,
    },
    {
        id: "bubbles-dark",
        name: "Dark Bubbles",
        patternType: "bubbles",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        secondaryColor: "#a1a1aa",
        size: 40,
        thickness: 2,
        opacity: 55,
    },
    {
        id: "bubbles-neon",
        name: "Neon Bubbles",
        patternType: "bubbles",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#d946ef",
        size: 34,
        thickness: 2,
        opacity: 68,
    },
    {
        id: "bubbles-lime",
        name: "Lime Bubbles",
        patternType: "bubbles",
        backgroundColor: "#1a2e05",
        patternColor: "#84cc16",
        secondaryColor: "#bef264",
        size: 38,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "bubbles-pearl",
        name: "Pearl Bubbles",
        patternType: "bubbles",
        backgroundColor: "#f8fafc",
        patternColor: "#94a3b8",
        secondaryColor: "#cbd5e1",
        size: 44,
        thickness: 1,
        opacity: 40,
    },
    {
        id: "bubbles-orange",
        name: "Orange Soda",
        patternType: "bubbles",
        backgroundColor: "#431407",
        patternColor: "#fb923c",
        secondaryColor: "#fdba74",
        size: 36,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "bubbles-berry",
        name: "Berry Soda",
        patternType: "bubbles",
        backgroundColor: "#4a044e",
        patternColor: "#d946ef",
        secondaryColor: "#fb7185",
        size: 40,
        thickness: 3,
        opacity: 55,
    },
]);

const scalesPresets = createPresets([
    {
        id: "scales-ocean",
        name: "Ocean Scales",
        patternType: "scales",
        backgroundColor: "#082f49",
        patternColor: "#38bdf8",
        secondaryColor: "#67e8f9",
        size: 44,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "scales-mermaid",
        name: "Mermaid",
        patternType: "scales",
        backgroundColor: "#042f2e",
        patternColor: "#2dd4bf",
        secondaryColor: "#c084fc",
        size: 42,
        thickness: 2,
        opacity: 64,
    },
    {
        id: "scales-gold",
        name: "Golden Scales",
        patternType: "scales",
        backgroundColor: "#422006",
        patternColor: "#eab308",
        secondaryColor: "#fef08a",
        size: 40,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "scales-black",
        name: "Black Scales",
        patternType: "scales",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        secondaryColor: "#27272a",
        size: 38,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "scales-purple",
        name: "Purple Scales",
        patternType: "scales",
        backgroundColor: "#2e1065",
        patternColor: "#8b5cf6",
        secondaryColor: "#d946ef",
        size: 42,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "scales-rose",
        name: "Rose Scales",
        patternType: "scales",
        backgroundColor: "#500724",
        patternColor: "#ec4899",
        secondaryColor: "#fda4af",
        size: 38,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "scales-jade",
        name: "Jade Scales",
        patternType: "scales",
        backgroundColor: "#022c22",
        patternColor: "#10b981",
        secondaryColor: "#6ee7b7",
        size: 46,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "scales-ice",
        name: "Ice Scales",
        patternType: "scales",
        backgroundColor: "#f0f9ff",
        patternColor: "#38bdf8",
        secondaryColor: "#bae6fd",
        size: 44,
        thickness: 2,
        opacity: 34,
    },
    {
        id: "scales-coral",
        name: "Coral Scales",
        patternType: "scales",
        backgroundColor: "#fff1f2",
        patternColor: "#fb7185",
        secondaryColor: "#fdba74",
        size: 40,
        thickness: 2,
        opacity: 42,
    },
    {
        id: "scales-steel",
        name: "Steel Scales",
        patternType: "scales",
        backgroundColor: "#18181b",
        patternColor: "#71717a",
        secondaryColor: "#a1a1aa",
        size: 36,
        thickness: 1,
        opacity: 48,
    },
]);

const dotsPresets = createPresets([
    {
        id: "dots-micro",
        name: "Micro Dots",
        patternType: "dots",
        backgroundColor: "#ffffff",
        patternColor: "#64748b",
        size: 10,
        thickness: 1,
        opacity: 32,
    },
    {
        id: "dots-soft",
        name: "Soft Dots",
        patternType: "dots",
        backgroundColor: "#f8fafc",
        patternColor: "#94a3b8",
        size: 22,
        thickness: 2,
        opacity: 32,
    },
    {
        id: "dots-ink",
        name: "Ink Dots",
        patternType: "dots",
        backgroundColor: "#ffffff",
        patternColor: "#18181b",
        size: 26,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "dots-blue",
        name: "Blue Dots",
        patternType: "dots",
        backgroundColor: "#172554",
        patternColor: "#60a5fa",
        size: 24,
        thickness: 2,
        opacity: 75,
    },
    {
        id: "dots-cyan",
        name: "Cyan Dots",
        patternType: "dots",
        backgroundColor: "#083344",
        patternColor: "#67e8f9",
        size: 20,
        thickness: 2,
        opacity: 68,
    },
    {
        id: "dots-violet",
        name: "Violet Dots",
        patternType: "dots",
        backgroundColor: "#2e1065",
        patternColor: "#c084fc",
        size: 26,
        thickness: 2,
        opacity: 72,
    },
    {
        id: "dots-pink",
        name: "Pink Dots",
        patternType: "dots",
        backgroundColor: "#500724",
        patternColor: "#f472b6",
        size: 26,
        thickness: 2,
        opacity: 68,
    },
    {
        id: "dots-emerald",
        name: "Emerald Dots",
        patternType: "dots",
        backgroundColor: "#022c22",
        patternColor: "#34d399",
        size: 22,
        thickness: 2,
        opacity: 68,
    },
    {
        id: "dots-gold",
        name: "Gold Dots",
        patternType: "dots",
        backgroundColor: "#2d1b05",
        patternColor: "#f59e0b",
        size: 28,
        thickness: 3,
        opacity: 62,
    },
    {
        id: "dots-large",
        name: "Large Dots",
        patternType: "dots",
        backgroundColor: "#18181b",
        patternColor: "#f4f4f5",
        size: 46,
        thickness: 6,
        opacity: 48,
    },
    {
        id: "dots-neon",
        name: "Neon Dots",
        patternType: "dots",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        size: 18,
        thickness: 2,
        opacity: 82,
    },
    {
        id: "dots-coral",
        name: "Coral Dots",
        patternType: "dots",
        backgroundColor: "#fff1f2",
        patternColor: "#fb7185",
        size: 26,
        thickness: 3,
        opacity: 48,
    },
]);

const polkaDotsPresets = createPresets([
    {
        id: "polka-classic",
        name: "Classic Polka",
        patternType: "polkaDots",
        backgroundColor: "#ffffff",
        patternColor: "#18181b",
        secondaryColor: "#18181b",
        size: 34,
        thickness: 3,
        opacity: 72,
    },
    {
        id: "polka-red",
        name: "Red Polka",
        patternType: "polkaDots",
        backgroundColor: "#fff7ed",
        patternColor: "#ef4444",
        secondaryColor: "#fb7185",
        size: 36,
        thickness: 3,
        opacity: 68,
    },
    {
        id: "polka-candy",
        name: "Candy Polka",
        patternType: "polkaDots",
        backgroundColor: "#fdf2f8",
        patternColor: "#ec4899",
        secondaryColor: "#8b5cf6",
        size: 34,
        thickness: 3,
        opacity: 62,
    },
    {
        id: "polka-ocean",
        name: "Ocean Polka",
        patternType: "polkaDots",
        backgroundColor: "#082f49",
        patternColor: "#38bdf8",
        secondaryColor: "#22d3ee",
        size: 34,
        thickness: 3,
        opacity: 65,
    },
    {
        id: "polka-mint",
        name: "Mint Polka",
        patternType: "polkaDots",
        backgroundColor: "#ecfdf5",
        patternColor: "#10b981",
        secondaryColor: "#5eead4",
        size: 38,
        thickness: 3,
        opacity: 52,
    },
    {
        id: "polka-night",
        name: "Night Polka",
        patternType: "polkaDots",
        backgroundColor: "#09090b",
        patternColor: "#a78bfa",
        secondaryColor: "#22d3ee",
        size: 32,
        thickness: 3,
        opacity: 62,
    },
    {
        id: "polka-peach",
        name: "Peach Polka",
        patternType: "polkaDots",
        backgroundColor: "#fff7ed",
        patternColor: "#fb923c",
        secondaryColor: "#fda4af",
        size: 40,
        thickness: 3,
        opacity: 48,
    },
    {
        id: "polka-lavender",
        name: "Lavender Polka",
        patternType: "polkaDots",
        backgroundColor: "#f5f3ff",
        patternColor: "#8b5cf6",
        secondaryColor: "#c084fc",
        size: 36,
        thickness: 3,
        opacity: 48,
    },
    {
        id: "polka-yellow",
        name: "Sunny Polka",
        patternType: "polkaDots",
        backgroundColor: "#fffbeb",
        patternColor: "#eab308",
        secondaryColor: "#fb923c",
        size: 34,
        thickness: 3,
        opacity: 52,
    },
    {
        id: "polka-mono",
        name: "Mono Polka",
        patternType: "polkaDots",
        backgroundColor: "#18181b",
        patternColor: "#71717a",
        secondaryColor: "#d4d4d8",
        size: 38,
        thickness: 3,
        opacity: 50,
    },
]);

const circlesPresets = createPresets([
    {
        id: "circles-blue",
        name: "Blue Circles",
        patternType: "circles",
        backgroundColor: "#172554",
        patternColor: "#60a5fa",
        secondaryColor: "#22d3ee",
        size: 54,
        thickness: 2,
        opacity: 65,
    },
    {
        id: "circles-violet",
        name: "Violet Circles",
        patternType: "circles",
        backgroundColor: "#2e1065",
        patternColor: "#a78bfa",
        secondaryColor: "#f472b6",
        size: 58,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "circles-emerald",
        name: "Emerald Circles",
        patternType: "circles",
        backgroundColor: "#022c22",
        patternColor: "#34d399",
        secondaryColor: "#a3e635",
        size: 52,
        thickness: 2,
        opacity: 56,
    },
    {
        id: "circles-sunset",
        name: "Sunset Circles",
        patternType: "circles",
        backgroundColor: "#431407",
        patternColor: "#fb923c",
        secondaryColor: "#fb7185",
        size: 58,
        thickness: 2,
        opacity: 60,
    },
    {
        id: "circles-neon",
        name: "Neon Circles",
        patternType: "circles",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#d946ef",
        size: 48,
        thickness: 2,
        opacity: 72,
    },
    {
        id: "circles-mono",
        name: "Mono Circles",
        patternType: "circles",
        backgroundColor: "#ffffff",
        patternColor: "#18181b",
        secondaryColor: "#94a3b8",
        size: 56,
        thickness: 2,
        opacity: 28,
    },
    {
        id: "circles-candy",
        name: "Candy Circles",
        patternType: "circles",
        backgroundColor: "#fdf2f8",
        patternColor: "#ec4899",
        secondaryColor: "#8b5cf6",
        size: 54,
        thickness: 2,
        opacity: 48,
    },
    {
        id: "circles-orange",
        name: "Orange Circles",
        patternType: "circles",
        backgroundColor: "#431407",
        patternColor: "#f97316",
        secondaryColor: "#facc15",
        size: 50,
        thickness: 2,
        opacity: 56,
    },
    {
        id: "circles-aqua",
        name: "Aqua Circles",
        patternType: "circles",
        backgroundColor: "#083344",
        patternColor: "#06b6d4",
        secondaryColor: "#5eead4",
        size: 60,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "circles-dark",
        name: "Dark Circles",
        patternType: "circles",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        secondaryColor: "#a1a1aa",
        size: 52,
        thickness: 2,
        opacity: 48,
    },
]);

const ringsPresets = createPresets([
    {
        id: "rings-fine",
        name: "Fine Rings",
        patternType: "rings",
        backgroundColor: "#ffffff",
        patternColor: "#64748b",
        size: 36,
        thickness: 1,
        opacity: 26,
    },
    {
        id: "rings-blue",
        name: "Blue Rings",
        patternType: "rings",
        backgroundColor: "#172554",
        patternColor: "#60a5fa",
        size: 44,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "rings-cyan",
        name: "Cyan Rings",
        patternType: "rings",
        backgroundColor: "#083344",
        patternColor: "#22d3ee",
        size: 38,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "rings-violet",
        name: "Violet Rings",
        patternType: "rings",
        backgroundColor: "#2e1065",
        patternColor: "#a78bfa",
        size: 46,
        thickness: 3,
        opacity: 62,
    },
    {
        id: "rings-rose",
        name: "Rose Rings",
        patternType: "rings",
        backgroundColor: "#500724",
        patternColor: "#fb7185",
        size: 42,
        thickness: 3,
        opacity: 58,
    },
    {
        id: "rings-emerald",
        name: "Emerald Rings",
        patternType: "rings",
        backgroundColor: "#022c22",
        patternColor: "#34d399",
        size: 44,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "rings-gold",
        name: "Gold Rings",
        patternType: "rings",
        backgroundColor: "#422006",
        patternColor: "#facc15",
        size: 48,
        thickness: 3,
        opacity: 55,
    },
    {
        id: "rings-neon",
        name: "Neon Rings",
        patternType: "rings",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        size: 36,
        thickness: 2,
        opacity: 76,
    },
    {
        id: "rings-dark",
        name: "Dark Rings",
        patternType: "rings",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        size: 44,
        thickness: 2,
        opacity: 55,
    },
    {
        id: "rings-pastel",
        name: "Pastel Rings",
        patternType: "rings",
        backgroundColor: "#f5f3ff",
        patternColor: "#c084fc",
        size: 48,
        thickness: 3,
        opacity: 34,
    },
]);

const zigzagPresets = createPresets([
    {
        id: "zigzag-black",
        name: "Black Zigzag",
        patternType: "zigzag",
        backgroundColor: "#ffffff",
        patternColor: "#18181b",
        secondaryColor: "#52525b",
        size: 36,
        opacity: 42,
    },
    {
        id: "zigzag-blue",
        name: "Blue Zigzag",
        patternType: "zigzag",
        backgroundColor: "#172554",
        patternColor: "#3b82f6",
        secondaryColor: "#60a5fa",
        size: 40,
        opacity: 62,
    },
    {
        id: "zigzag-cyan",
        name: "Cyan Zigzag",
        patternType: "zigzag",
        backgroundColor: "#083344",
        patternColor: "#06b6d4",
        secondaryColor: "#67e8f9",
        size: 34,
        opacity: 62,
    },
    {
        id: "zigzag-violet",
        name: "Violet Zigzag",
        patternType: "zigzag",
        backgroundColor: "#2e1065",
        patternColor: "#8b5cf6",
        secondaryColor: "#d946ef",
        size: 38,
        opacity: 64,
    },
    {
        id: "zigzag-candy",
        name: "Candy Zigzag",
        patternType: "zigzag",
        backgroundColor: "#fdf2f8",
        patternColor: "#ec4899",
        secondaryColor: "#8b5cf6",
        size: 42,
        opacity: 48,
    },
    {
        id: "zigzag-emerald",
        name: "Emerald Zigzag",
        patternType: "zigzag",
        backgroundColor: "#022c22",
        patternColor: "#10b981",
        secondaryColor: "#84cc16",
        size: 36,
        opacity: 58,
    },
    {
        id: "zigzag-sunset",
        name: "Sunset Zigzag",
        patternType: "zigzag",
        backgroundColor: "#431407",
        patternColor: "#f97316",
        secondaryColor: "#facc15",
        size: 40,
        opacity: 65,
    },
    {
        id: "zigzag-dark",
        name: "Dark Zigzag",
        patternType: "zigzag",
        backgroundColor: "#09090b",
        patternColor: "#27272a",
        secondaryColor: "#52525b",
        size: 34,
        opacity: 72,
    },
    {
        id: "zigzag-mint",
        name: "Mint Zigzag",
        patternType: "zigzag",
        backgroundColor: "#ecfdf5",
        patternColor: "#34d399",
        secondaryColor: "#5eead4",
        size: 42,
        opacity: 40,
    },
    {
        id: "zigzag-retro",
        name: "Retro Zigzag",
        patternType: "zigzag",
        backgroundColor: "#7c2d12",
        patternColor: "#fb923c",
        secondaryColor: "#fde047",
        size: 38,
        opacity: 75,
    },
]);

const chevronPresets = createPresets([
    {
        id: "chevron-black",
        name: "Black Chevron",
        patternType: "chevron",
        backgroundColor: "#ffffff",
        patternColor: "#18181b",
        secondaryColor: "#18181b",
        size: 40,
        thickness: 2,
        opacity: 42,
    },
    {
        id: "chevron-blue",
        name: "Blue Chevron",
        patternType: "chevron",
        backgroundColor: "#172554",
        patternColor: "#3b82f6",
        secondaryColor: "#60a5fa",
        size: 42,
        thickness: 2,
        opacity: 65,
    },
    {
        id: "chevron-cyan",
        name: "Cyan Chevron",
        patternType: "chevron",
        backgroundColor: "#083344",
        patternColor: "#06b6d4",
        secondaryColor: "#22d3ee",
        size: 36,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "chevron-violet",
        name: "Violet Chevron",
        patternType: "chevron",
        backgroundColor: "#2e1065",
        patternColor: "#8b5cf6",
        secondaryColor: "#c084fc",
        size: 42,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "chevron-rose",
        name: "Rose Chevron",
        patternType: "chevron",
        backgroundColor: "#500724",
        patternColor: "#ec4899",
        secondaryColor: "#fb7185",
        size: 38,
        thickness: 2,
        opacity: 60,
    },
    {
        id: "chevron-gold",
        name: "Gold Chevron",
        patternType: "chevron",
        backgroundColor: "#422006",
        patternColor: "#f59e0b",
        secondaryColor: "#fde047",
        size: 44,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "chevron-mint",
        name: "Mint Chevron",
        patternType: "chevron",
        backgroundColor: "#ecfdf5",
        patternColor: "#10b981",
        secondaryColor: "#5eead4",
        size: 40,
        thickness: 2,
        opacity: 38,
    },
    {
        id: "chevron-dark",
        name: "Dark Chevron",
        patternType: "chevron",
        backgroundColor: "#09090b",
        patternColor: "#3f3f46",
        secondaryColor: "#71717a",
        size: 36,
        thickness: 2,
        opacity: 58,
    },
    {
        id: "chevron-coral",
        name: "Coral Chevron",
        patternType: "chevron",
        backgroundColor: "#fff1f2",
        patternColor: "#fb7185",
        secondaryColor: "#fdba74",
        size: 44,
        thickness: 2,
        opacity: 42,
    },
    {
        id: "chevron-neon",
        name: "Neon Chevron",
        patternType: "chevron",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#d946ef",
        size: 38,
        thickness: 2,
        opacity: 70,
    },
]);

const bricksPresets = createPresets([
    {
        id: "bricks-classic",
        name: "Classic Brick",
        patternType: "bricks",
        backgroundColor: "#7f1d1d",
        patternColor: "#fecaca",
        secondaryColor: "#450a0a",
        size: 52,
        thickness: 2,
        opacity: 55,
    },
    {
        id: "bricks-terracotta",
        name: "Terracotta",
        patternType: "bricks",
        backgroundColor: "#9a3412",
        patternColor: "#fed7aa",
        secondaryColor: "#7c2d12",
        size: 56,
        thickness: 2,
        opacity: 54,
    },
    {
        id: "bricks-white",
        name: "White Brick",
        patternType: "bricks",
        backgroundColor: "#f8fafc",
        patternColor: "#cbd5e1",
        secondaryColor: "#94a3b8",
        size: 54,
        thickness: 2,
        opacity: 48,
    },
    {
        id: "bricks-black",
        name: "Black Brick",
        patternType: "bricks",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        secondaryColor: "#27272a",
        size: 50,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "bricks-blue",
        name: "Blue Brick",
        patternType: "bricks",
        backgroundColor: "#172554",
        patternColor: "#60a5fa",
        secondaryColor: "#1e40af",
        size: 54,
        thickness: 2,
        opacity: 55,
    },
    {
        id: "bricks-cyan",
        name: "Cyan Brick",
        patternType: "bricks",
        backgroundColor: "#083344",
        patternColor: "#22d3ee",
        secondaryColor: "#155e75",
        size: 48,
        thickness: 2,
        opacity: 55,
    },
    {
        id: "bricks-emerald",
        name: "Emerald Brick",
        patternType: "bricks",
        backgroundColor: "#022c22",
        patternColor: "#34d399",
        secondaryColor: "#065f46",
        size: 52,
        thickness: 2,
        opacity: 52,
    },
    {
        id: "bricks-purple",
        name: "Purple Brick",
        patternType: "bricks",
        backgroundColor: "#2e1065",
        patternColor: "#c084fc",
        secondaryColor: "#6b21a8",
        size: 54,
        thickness: 2,
        opacity: 54,
    },
    {
        id: "bricks-sand",
        name: "Sandstone",
        patternType: "bricks",
        backgroundColor: "#fef3c7",
        patternColor: "#d97706",
        secondaryColor: "#f59e0b",
        size: 58,
        thickness: 2,
        opacity: 36,
    },
    {
        id: "bricks-concrete",
        name: "Concrete",
        patternType: "bricks",
        backgroundColor: "#d4d4d8",
        patternColor: "#71717a",
        secondaryColor: "#a1a1aa",
        size: 56,
        thickness: 2,
        opacity: 38,
    },
]);

const trianglesPresets = createPresets([
    {
        id: "triangles-blue",
        name: "Blue Triangles",
        patternType: "triangles",
        backgroundColor: "#172554",
        patternColor: "#3b82f6",
        secondaryColor: "#22d3ee",
        size: 48,
        opacity: 65,
    },
    {
        id: "triangles-violet",
        name: "Violet Triangles",
        patternType: "triangles",
        backgroundColor: "#2e1065",
        patternColor: "#8b5cf6",
        secondaryColor: "#d946ef",
        size: 48,
        opacity: 68,
    },
    {
        id: "triangles-emerald",
        name: "Emerald Triangles",
        patternType: "triangles",
        backgroundColor: "#022c22",
        patternColor: "#10b981",
        secondaryColor: "#84cc16",
        size: 50,
        opacity: 62,
    },
    {
        id: "triangles-sunset",
        name: "Sunset Triangles",
        patternType: "triangles",
        backgroundColor: "#431407",
        patternColor: "#f97316",
        secondaryColor: "#facc15",
        size: 54,
        opacity: 72,
    },
    {
        id: "triangles-candy",
        name: "Candy Triangles",
        patternType: "triangles",
        backgroundColor: "#fdf2f8",
        patternColor: "#ec4899",
        secondaryColor: "#8b5cf6",
        size: 48,
        opacity: 48,
    },
    {
        id: "triangles-dark",
        name: "Dark Triangles",
        patternType: "triangles",
        backgroundColor: "#09090b",
        patternColor: "#3f3f46",
        secondaryColor: "#71717a",
        size: 46,
        opacity: 62,
    },
    {
        id: "triangles-neon",
        name: "Neon Triangles",
        patternType: "triangles",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#d946ef",
        size: 44,
        opacity: 72,
    },
    {
        id: "triangles-lavender",
        name: "Lavender Triangles",
        patternType: "triangles",
        backgroundColor: "#f5f3ff",
        patternColor: "#a78bfa",
        secondaryColor: "#f9a8d4",
        size: 52,
        opacity: 40,
    },
    {
        id: "triangles-gold",
        name: "Gold Triangles",
        patternType: "triangles",
        backgroundColor: "#422006",
        patternColor: "#eab308",
        secondaryColor: "#fb923c",
        size: 50,
        opacity: 65,
    },
    {
        id: "triangles-ice",
        name: "Ice Triangles",
        patternType: "triangles",
        backgroundColor: "#f0f9ff",
        patternColor: "#38bdf8",
        secondaryColor: "#a5f3fc",
        size: 54,
        opacity: 38,
    },
]);

const confettiPresets = createPresets([
    {
        id: "confetti-party",
        name: "Party",
        patternType: "confetti",
        backgroundColor: "#ffffff",
        patternColor: "#ec4899",
        secondaryColor: "#3b82f6",
        size: 32,
        thickness: 2,
        opacity: 70,
    },
    {
        id: "confetti-candy",
        name: "Candy",
        patternType: "confetti",
        backgroundColor: "#fdf2f8",
        patternColor: "#f472b6",
        secondaryColor: "#8b5cf6",
        size: 30,
        thickness: 2,
        opacity: 62,
    },
    {
        id: "confetti-ocean",
        name: "Ocean",
        patternType: "confetti",
        backgroundColor: "#082f49",
        patternColor: "#22d3ee",
        secondaryColor: "#3b82f6",
        size: 30,
        thickness: 2,
        opacity: 68,
    },
    {
        id: "confetti-neon",
        name: "Neon",
        patternType: "confetti",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#d946ef",
        size: 28,
        thickness: 2,
        opacity: 80,
    },
    {
        id: "confetti-sunset",
        name: "Sunset",
        patternType: "confetti",
        backgroundColor: "#431407",
        patternColor: "#fb923c",
        secondaryColor: "#fb7185",
        size: 34,
        thickness: 2,
        opacity: 64,
    },
    {
        id: "confetti-mint",
        name: "Mint",
        patternType: "confetti",
        backgroundColor: "#ecfdf5",
        patternColor: "#10b981",
        secondaryColor: "#38bdf8",
        size: 32,
        thickness: 2,
        opacity: 48,
    },
    {
        id: "confetti-purple",
        name: "Purple",
        patternType: "confetti",
        backgroundColor: "#2e1065",
        patternColor: "#c084fc",
        secondaryColor: "#f472b6",
        size: 30,
        thickness: 2,
        opacity: 70,
    },
    {
        id: "confetti-gold",
        name: "Gold",
        patternType: "confetti",
        backgroundColor: "#18181b",
        patternColor: "#facc15",
        secondaryColor: "#fb923c",
        size: 34,
        thickness: 2,
        opacity: 68,
    },
    {
        id: "confetti-pastel",
        name: "Pastel",
        patternType: "confetti",
        backgroundColor: "#fafafa",
        patternColor: "#f9a8d4",
        secondaryColor: "#a5b4fc",
        size: 34,
        thickness: 2,
        opacity: 50,
    },
    {
        id: "confetti-mono",
        name: "Monochrome",
        patternType: "confetti",
        backgroundColor: "#ffffff",
        patternColor: "#52525b",
        secondaryColor: "#a1a1aa",
        size: 32,
        thickness: 2,
        opacity: 42,
    },
]);

const gridPresets = createPresets([
    {
        id: "grid-blueprint",
        name: "Blueprint",
        patternType: "grid",
        backgroundColor: "#172554",
        patternColor: "#60a5fa",
        size: 32,
        thickness: 1,
        opacity: 55,
    },
    {
        id: "grid-graph-paper",
        name: "Graph Paper",
        patternType: "grid",
        backgroundColor: "#ffffff",
        patternColor: "#94a3b8",
        size: 24,
        thickness: 1,
        opacity: 24,
    },
    {
        id: "grid-dark",
        name: "Dark Grid",
        patternType: "grid",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        size: 32,
        thickness: 1,
        opacity: 45,
    },
    {
        id: "grid-cyan",
        name: "Cyan Grid",
        patternType: "grid",
        backgroundColor: "#083344",
        patternColor: "#22d3ee",
        size: 28,
        thickness: 1,
        opacity: 55,
    },
    {
        id: "grid-purple",
        name: "Purple Grid",
        patternType: "grid",
        backgroundColor: "#2e1065",
        patternColor: "#c084fc",
        size: 32,
        thickness: 1,
        opacity: 45,
    },
    {
        id: "grid-terminal",
        name: "Terminal Grid",
        patternType: "grid",
        backgroundColor: "#052e16",
        patternColor: "#4ade80",
        size: 30,
        thickness: 1,
        opacity: 45,
    },
    {
        id: "grid-micro",
        name: "Micro Grid",
        patternType: "grid",
        backgroundColor: "#020617",
        patternColor: "#64748b",
        size: 12,
        thickness: 1,
        opacity: 35,
    },
    {
        id: "grid-large",
        name: "Large Grid",
        patternType: "grid",
        backgroundColor: "#020617",
        patternColor: "#475569",
        size: 64,
        thickness: 1,
        opacity: 52,
    },
    {
        id: "grid-pink",
        name: "Pink Grid",
        patternType: "grid",
        backgroundColor: "#500724",
        patternColor: "#f472b6",
        size: 30,
        thickness: 1,
        opacity: 45,
    },
    {
        id: "grid-mint",
        name: "Mint Grid",
        patternType: "grid",
        backgroundColor: "#ecfdf5",
        patternColor: "#34d399",
        size: 32,
        thickness: 1,
        opacity: 28,
    },
]);

const checkerPresets = createPresets([
    {
        id: "checker-classic",
        name: "Classic Checker",
        patternType: "checker",
        backgroundColor: "#ffffff",
        patternColor: "#18181b",
        secondaryColor: "#ffffff",
        size: 36,
        opacity: 100,
    },
    {
        id: "checker-dark",
        name: "Dark Checker",
        patternType: "checker",
        backgroundColor: "#09090b",
        patternColor: "#18181b",
        secondaryColor: "#3f3f46",
        size: 38,
        opacity: 100,
    },
    {
        id: "checker-blue",
        name: "Blue Checker",
        patternType: "checker",
        backgroundColor: "#172554",
        patternColor: "#1d4ed8",
        secondaryColor: "#60a5fa",
        size: 40,
        opacity: 78,
    },
    {
        id: "checker-pink",
        name: "Pink Checker",
        patternType: "checker",
        backgroundColor: "#fdf2f8",
        patternColor: "#f9a8d4",
        secondaryColor: "#c4b5fd",
        size: 42,
        opacity: 70,
    },
    {
        id: "checker-mint",
        name: "Mint Checker",
        patternType: "checker",
        backgroundColor: "#ecfdf5",
        patternColor: "#a7f3d0",
        secondaryColor: "#bae6fd",
        size: 42,
        opacity: 68,
    },
    {
        id: "checker-orange",
        name: "Orange Checker",
        patternType: "checker",
        backgroundColor: "#431407",
        patternColor: "#f97316",
        secondaryColor: "#facc15",
        size: 42,
        opacity: 88,
    },
    {
        id: "checker-violet",
        name: "Violet Checker",
        patternType: "checker",
        backgroundColor: "#2e1065",
        patternColor: "#7c3aed",
        secondaryColor: "#c084fc",
        size: 38,
        opacity: 78,
    },
    {
        id: "checker-sage",
        name: "Sage Checker",
        patternType: "checker",
        backgroundColor: "#f7fee7",
        patternColor: "#bef264",
        secondaryColor: "#a7f3d0",
        size: 44,
        opacity: 58,
    },
]);

const crosshatchPresets = createPresets([
    {
        id: "crosshatch-ink",
        name: "Ink Crosshatch",
        patternType: "crosshatch",
        backgroundColor: "#ffffff",
        patternColor: "#52525b",
        secondaryColor: "#a1a1aa",
        size: 28,
        thickness: 1,
        opacity: 32,
        angle: 45,
    },
    {
        id: "crosshatch-blue",
        name: "Blue Crosshatch",
        patternType: "crosshatch",
        backgroundColor: "#172554",
        patternColor: "#3b82f6",
        secondaryColor: "#60a5fa",
        size: 34,
        thickness: 1,
        opacity: 52,
        angle: 45,
    },
    {
        id: "crosshatch-cyan",
        name: "Cyan Crosshatch",
        patternType: "crosshatch",
        backgroundColor: "#083344",
        patternColor: "#06b6d4",
        secondaryColor: "#22d3ee",
        size: 32,
        thickness: 1,
        opacity: 55,
        angle: 60,
    },
    {
        id: "crosshatch-purple",
        name: "Purple Crosshatch",
        patternType: "crosshatch",
        backgroundColor: "#2e1065",
        patternColor: "#8b5cf6",
        secondaryColor: "#d946ef",
        size: 36,
        thickness: 1,
        opacity: 55,
        angle: 45,
    },
    {
        id: "crosshatch-emerald",
        name: "Emerald Crosshatch",
        patternType: "crosshatch",
        backgroundColor: "#022c22",
        patternColor: "#10b981",
        secondaryColor: "#34d399",
        size: 34,
        thickness: 1,
        opacity: 52,
        angle: 45,
    },
    {
        id: "crosshatch-neon",
        name: "Neon Mesh",
        patternType: "crosshatch",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#d946ef",
        size: 38,
        thickness: 1,
        opacity: 68,
        angle: 60,
    },
    {
        id: "crosshatch-dark",
        name: "Dark Mesh",
        patternType: "crosshatch",
        backgroundColor: "#09090b",
        patternColor: "#3f3f46",
        secondaryColor: "#52525b",
        size: 32,
        thickness: 1,
        opacity: 55,
        angle: 45,
    },
    {
        id: "crosshatch-soft",
        name: "Soft Mesh",
        patternType: "crosshatch",
        backgroundColor: "#f8fafc",
        patternColor: "#cbd5e1",
        secondaryColor: "#e2e8f0",
        size: 38,
        thickness: 1,
        opacity: 40,
        angle: 45,
    },
]);

const stripePresets = createPresets([
    {
        id: "stripes-pinstripe",
        name: "Pinstripe",
        patternType: "vertical",
        backgroundColor: "#ffffff",
        patternColor: "#64748b",
        size: 18,
        thickness: 1,
        opacity: 28,
    },
    {
        id: "stripes-horizontal",
        name: "Fine Horizontal",
        patternType: "horizontal",
        backgroundColor: "#ffffff",
        patternColor: "#64748b",
        size: 18,
        thickness: 1,
        opacity: 26,
    },
    {
        id: "stripes-diagonal",
        name: "Classic Diagonal",
        patternType: "diagonal",
        backgroundColor: "#f8fafc",
        patternColor: "#64748b",
        size: 24,
        thickness: 2,
        opacity: 34,
        angle: 45,
    },
    {
        id: "stripes-barber",
        name: "Barber Blue",
        patternType: "diagonal",
        backgroundColor: "#ffffff",
        patternColor: "#3b82f6",
        size: 24,
        thickness: 6,
        opacity: 70,
        angle: 45,
    },
    {
        id: "stripes-caution",
        name: "Caution",
        patternType: "diagonal",
        backgroundColor: "#18181b",
        patternColor: "#facc15",
        size: 28,
        thickness: 8,
        opacity: 88,
        angle: 45,
    },
    {
        id: "stripes-candy",
        name: "Candy Stripe",
        patternType: "diagonal",
        backgroundColor: "#fff1f2",
        patternColor: "#fb7185",
        size: 26,
        thickness: 6,
        opacity: 62,
        angle: 45,
    },
    {
        id: "stripes-neon",
        name: "Neon Stripe",
        patternType: "diagonal",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        size: 22,
        thickness: 3,
        opacity: 70,
        angle: 120,
    },
    {
        id: "stripes-purple",
        name: "Purple Stripe",
        patternType: "diagonal",
        backgroundColor: "#2e1065",
        patternColor: "#c084fc",
        size: 28,
        thickness: 4,
        opacity: 58,
        angle: 135,
    },
    {
        id: "stripes-green",
        name: "Green Stripe",
        patternType: "diagonal",
        backgroundColor: "#052e16",
        patternColor: "#4ade80",
        size: 24,
        thickness: 3,
        opacity: 54,
        angle: 45,
    },
    {
        id: "stripes-orange",
        name: "Orange Stripe",
        patternType: "diagonal",
        backgroundColor: "#431407",
        patternColor: "#fb923c",
        size: 30,
        thickness: 5,
        opacity: 60,
        angle: 45,
    },
    {
        id: "stripes-dark",
        name: "Dark Stripe",
        patternType: "vertical",
        backgroundColor: "#09090b",
        patternColor: "#3f3f46",
        size: 18,
        thickness: 2,
        opacity: 52,
    },
    {
        id: "stripes-paper",
        name: "Notebook",
        patternType: "horizontal",
        backgroundColor: "#ffffff",
        patternColor: "#93c5fd",
        size: 26,
        thickness: 1,
        opacity: 42,
    },
]);

const weavePresets = createPresets([
    {
        id: "weave-linen",
        name: "Linen",
        patternType: "weave",
        backgroundColor: "#fafaf9",
        patternColor: "#a8a29e",
        secondaryColor: "#d6d3d1",
        size: 34,
        thickness: 2,
        opacity: 35,
        angle: 45,
    },
    {
        id: "weave-carbon",
        name: "Carbon Fiber",
        patternType: "weave",
        backgroundColor: "#09090b",
        patternColor: "#27272a",
        secondaryColor: "#52525b",
        size: 22,
        thickness: 3,
        opacity: 72,
        angle: 45,
    },
    {
        id: "weave-blue",
        name: "Blue Weave",
        patternType: "weave",
        backgroundColor: "#172554",
        patternColor: "#3b82f6",
        secondaryColor: "#60a5fa",
        size: 34,
        thickness: 3,
        opacity: 58,
        angle: 45,
    },
    {
        id: "weave-cyan",
        name: "Cyan Weave",
        patternType: "weave",
        backgroundColor: "#083344",
        patternColor: "#06b6d4",
        secondaryColor: "#67e8f9",
        size: 32,
        thickness: 2,
        opacity: 58,
        angle: 45,
    },
    {
        id: "weave-purple",
        name: "Purple Weave",
        patternType: "weave",
        backgroundColor: "#2e1065",
        patternColor: "#8b5cf6",
        secondaryColor: "#d946ef",
        size: 36,
        thickness: 3,
        opacity: 60,
        angle: 45,
    },
    {
        id: "weave-emerald",
        name: "Emerald Weave",
        patternType: "weave",
        backgroundColor: "#022c22",
        patternColor: "#10b981",
        secondaryColor: "#6ee7b7",
        size: 34,
        thickness: 3,
        opacity: 55,
        angle: 45,
    },
    {
        id: "weave-rose",
        name: "Rose Weave",
        patternType: "weave",
        backgroundColor: "#500724",
        patternColor: "#ec4899",
        secondaryColor: "#fb7185",
        size: 34,
        thickness: 3,
        opacity: 58,
        angle: 45,
    },
    {
        id: "weave-gold",
        name: "Gold Weave",
        patternType: "weave",
        backgroundColor: "#422006",
        patternColor: "#eab308",
        secondaryColor: "#fbbf24",
        size: 36,
        thickness: 3,
        opacity: 58,
        angle: 45,
    },
    {
        id: "weave-neon",
        name: "Neon Weave",
        patternType: "weave",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#d946ef",
        size: 30,
        thickness: 2,
        opacity: 68,
        angle: 45,
    },
    {
        id: "weave-pastel",
        name: "Pastel Weave",
        patternType: "weave",
        backgroundColor: "#f5f3ff",
        patternColor: "#c4b5fd",
        secondaryColor: "#f9a8d4",
        size: 38,
        thickness: 2,
        opacity: 42,
        angle: 45,
    },
]);

export const patternPresetCategories: PatternPresetCategory[] = [
    {
        id: "honeycomb",
        name: "Honeycomb",
        presets: honeycombPresets,
    },
    {
        id: "diamonds",
        name: "Diamonds",
        presets: diamondsPresets,
    },
    {
        id: "waves",
        name: "Waves",
        presets: wavesPresets,
    },
    {
        id: "clouds",
        name: "Clouds",
        presets: cloudsPresets,
    },
    {
        id: "bubbles",
        name: "Bubbles",
        presets: bubblesPresets,
    },
    {
        id: "scales",
        name: "Scales",
        presets: scalesPresets,
    },
    {
        id: "dots",
        name: "Dots",
        presets: dotsPresets,
    },
    {
        id: "polka-dots",
        name: "Polka Dots",
        presets: polkaDotsPresets,
    },
    {
        id: "circles",
        name: "Circles",
        presets: circlesPresets,
    },
    {
        id: "rings",
        name: "Rings",
        presets: ringsPresets,
    },
    {
        id: "zigzag",
        name: "Zigzag",
        presets: zigzagPresets,
    },
    {
        id: "chevron",
        name: "Chevron",
        presets: chevronPresets,
    },
    {
        id: "bricks",
        name: "Bricks",
        presets: bricksPresets,
    },
    {
        id: "triangles",
        name: "Triangles",
        presets: trianglesPresets,
    },
    {
        id: "confetti",
        name: "Confetti",
        presets: confettiPresets,
    },
    {
        id: "grid",
        name: "Grid",
        presets: gridPresets,
    },
    {
        id: "checker",
        name: "Checker",
        presets: checkerPresets,
    },
    {
        id: "crosshatch",
        name: "Crosshatch",
        presets: crosshatchPresets,
    },
    {
        id: "stripes",
        name: "Stripes",
        presets: stripePresets,
    },
    {
        id: "weave",
        name: "Weave",
        presets: weavePresets,
    },
];

export const patternPresets = patternPresetCategories.flatMap(
    (category) => category.presets,
);
