import {
    PatternConfig,
    PatternPreset,
    PatternPresetCategory,
} from "./pattern.types";

export type PatternType =
    | "dots"
    | "polkaDots"
    | "grid"
    | "diagonal"
    | "horizontal"
    | "vertical"
    | "checker"
    | "diamonds"
    | "honeycomb"
    | "hexagons"
    | "crosshatch"
    | "rings"
    | "bubbles"
    | "waves"
    | "scales"
    | "clouds"
    | "triangles"
    | "zigzag"
    | "chevron"
    | "bricks"
    | "tiles"
    | "circles"
    | "confetti"
    | "stars"
    | "plus"
    | "weave";

const preset = (
    id: string,
    name: string,
    config: Partial<PatternConfig>,
): PatternPreset => ({
    id,
    name,
    config: {
        patternType: "dots",
        backgroundColor: "#0f172a",
        patternColor: "#8b5cf6",
        secondaryColor: "#ec4899",
        size: 32,
        thickness: 2,
        opacity: 80,
        scaleX: 100,
        scaleY: 100,
        elementOffsetX: 0,
        elementOffsetY: 0,
        gapX: 0,
        gapY: 0,
        angle: 45,
        positionX: 0,
        positionY: 0,
        ...config,
    },
});

const minimalPresets: PatternPreset[] = [
    preset("minimal-soft-dots", "Soft Dots", {
        patternType: "dots",
        backgroundColor: "#ffffff",
        patternColor: "#94a3b8",
        size: 24,
        thickness: 1,
        opacity: 35,
    }),
    preset("minimal-black-dots", "Black Dots", {
        patternType: "dots",
        backgroundColor: "#ffffff",
        patternColor: "#18181b",
        size: 28,
        thickness: 1,
        opacity: 25,
    }),
    preset("minimal-gray-grid", "Gray Grid", {
        patternType: "grid",
        backgroundColor: "#ffffff",
        patternColor: "#64748b",
        size: 32,
        thickness: 1,
        opacity: 18,
    }),
    preset("minimal-blue-grid", "Blue Grid", {
        patternType: "grid",
        backgroundColor: "#f8fafc",
        patternColor: "#3b82f6",
        size: 36,
        thickness: 1,
        opacity: 18,
    }),
    preset("minimal-lines", "Thin Lines", {
        patternType: "horizontal",
        backgroundColor: "#ffffff",
        patternColor: "#64748b",
        size: 28,
        thickness: 1,
        opacity: 20,
    }),
    preset("minimal-vertical", "Vertical Lines", {
        patternType: "vertical",
        backgroundColor: "#fafafa",
        patternColor: "#71717a",
        size: 32,
        thickness: 1,
        opacity: 20,
    }),
    preset("minimal-diagonal", "Soft Diagonal", {
        patternType: "diagonal",
        backgroundColor: "#ffffff",
        patternColor: "#94a3b8",
        size: 32,
        thickness: 1,
        opacity: 22,
        angle: 45,
    }),
    preset("minimal-cross", "Minimal Cross", {
        patternType: "crosshatch",
        backgroundColor: "#ffffff",
        patternColor: "#cbd5e1",
        secondaryColor: "#e2e8f0",
        size: 40,
        thickness: 1,
        opacity: 30,
        angle: 45,
    }),
    preset("minimal-rings", "Fine Rings", {
        patternType: "rings",
        backgroundColor: "#ffffff",
        patternColor: "#94a3b8",
        size: 34,
        thickness: 1,
        opacity: 22,
    }),
    preset("minimal-diamond", "Fine Diamond", {
        patternType: "diamonds",
        backgroundColor: "#ffffff",
        patternColor: "#94a3b8",
        secondaryColor: "#cbd5e1",
        size: 40,
        opacity: 25,
    }),
    preset("minimal-waves", "Soft Waves", {
        patternType: "waves",
        backgroundColor: "#ffffff",
        patternColor: "#94a3b8",
        secondaryColor: "#cbd5e1",
        size: 50,
        opacity: 28,
    }),
    preset("minimal-paper", "Paper", {
        patternType: "grid",
        backgroundColor: "#f8fafc",
        patternColor: "#cbd5e1",
        size: 20,
        thickness: 1,
        opacity: 35,
    }),
];

const gridPresets: PatternPreset[] = [
    preset("grid-blueprint", "Blueprint", {
        patternType: "grid",
        backgroundColor: "#172554",
        patternColor: "#60a5fa",
        size: 32,
        thickness: 1,
        opacity: 55,
    }),
    preset("grid-dark", "Dark Grid", {
        patternType: "grid",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        size: 32,
        thickness: 1,
        opacity: 45,
    }),
    preset("grid-cyan", "Cyan Grid", {
        patternType: "grid",
        backgroundColor: "#083344",
        patternColor: "#22d3ee",
        size: 28,
        thickness: 1,
        opacity: 55,
    }),
    preset("grid-purple", "Purple Grid", {
        patternType: "grid",
        backgroundColor: "#2e1065",
        patternColor: "#c084fc",
        size: 32,
        thickness: 1,
        opacity: 45,
    }),
    preset("grid-green", "Terminal Grid", {
        patternType: "grid",
        backgroundColor: "#052e16",
        patternColor: "#4ade80",
        size: 30,
        thickness: 1,
        opacity: 45,
    }),
    preset("grid-pink", "Pink Grid", {
        patternType: "grid",
        backgroundColor: "#500724",
        patternColor: "#f472b6",
        size: 28,
        thickness: 1,
        opacity: 45,
    }),
    preset("grid-orange", "Orange Grid", {
        patternType: "grid",
        backgroundColor: "#431407",
        patternColor: "#fb923c",
        size: 36,
        thickness: 1,
        opacity: 45,
    }),
    preset("grid-heavy", "Heavy Grid", {
        patternType: "grid",
        backgroundColor: "#18181b",
        patternColor: "#a1a1aa",
        size: 48,
        thickness: 2,
        opacity: 45,
    }),
    preset("grid-micro", "Micro Grid", {
        patternType: "grid",
        backgroundColor: "#0f172a",
        patternColor: "#64748b",
        size: 12,
        thickness: 1,
        opacity: 35,
    }),
    preset("grid-large", "Large Grid", {
        patternType: "grid",
        backgroundColor: "#020617",
        patternColor: "#475569",
        size: 64,
        thickness: 1,
        opacity: 55,
    }),
    preset("grid-white", "White Grid", {
        patternType: "grid",
        backgroundColor: "#f8fafc",
        patternColor: "#64748b",
        size: 32,
        thickness: 1,
        opacity: 22,
    }),
    preset("grid-lime", "Lime Grid", {
        patternType: "grid",
        backgroundColor: "#1a2e05",
        patternColor: "#a3e635",
        size: 32,
        thickness: 1,
        opacity: 48,
    }),
];

const dotsPresets: PatternPreset[] = [
    preset("dots-blue", "Blue Dots", {
        patternType: "dots",
        backgroundColor: "#172554",
        patternColor: "#60a5fa",
        size: 24,
        thickness: 2,
        opacity: 75,
    }),
    preset("dots-purple", "Purple Dots", {
        patternType: "dots",
        backgroundColor: "#2e1065",
        patternColor: "#c084fc",
        size: 26,
        thickness: 2,
        opacity: 75,
    }),
    preset("dots-pink", "Pink Dots", {
        patternType: "dots",
        backgroundColor: "#500724",
        patternColor: "#f472b6",
        size: 28,
        thickness: 2,
        opacity: 75,
    }),
    preset("dots-cyan", "Cyan Dots", {
        patternType: "dots",
        backgroundColor: "#083344",
        patternColor: "#67e8f9",
        size: 24,
        thickness: 2,
        opacity: 75,
    }),
    preset("dots-green", "Green Dots", {
        patternType: "dots",
        backgroundColor: "#052e16",
        patternColor: "#4ade80",
        size: 24,
        thickness: 2,
        opacity: 75,
    }),
    preset("dots-orange", "Orange Dots", {
        patternType: "dots",
        backgroundColor: "#431407",
        patternColor: "#fb923c",
        size: 28,
        thickness: 2,
        opacity: 75,
    }),
    preset("dots-large", "Large Dots", {
        patternType: "dots",
        backgroundColor: "#18181b",
        patternColor: "#f4f4f5",
        size: 44,
        thickness: 5,
        opacity: 55,
    }),
    preset("dots-micro", "Micro Dots", {
        patternType: "dots",
        backgroundColor: "#09090b",
        patternColor: "#a1a1aa",
        size: 12,
        thickness: 1,
        opacity: 45,
    }),
    preset("dots-white", "Paper Dots", {
        patternType: "dots",
        backgroundColor: "#ffffff",
        patternColor: "#64748b",
        size: 24,
        thickness: 1,
        opacity: 28,
    }),
    preset("dots-red", "Red Dots", {
        patternType: "dots",
        backgroundColor: "#450a0a",
        patternColor: "#f87171",
        size: 26,
        thickness: 2,
        opacity: 70,
    }),
    preset("dots-yellow", "Yellow Dots", {
        patternType: "dots",
        backgroundColor: "#422006",
        patternColor: "#fde047",
        size: 28,
        thickness: 2,
        opacity: 75,
    }),
    preset("dots-lavender", "Lavender Dots", {
        patternType: "dots",
        backgroundColor: "#f3e8ff",
        patternColor: "#8b5cf6",
        size: 24,
        thickness: 2,
        opacity: 45,
    }),
];

const geometricPresets: PatternPreset[] = [
    preset("geo-diamond-purple", "Purple Diamonds", {
        patternType: "diamonds",
        backgroundColor: "#1e1b4b",
        patternColor: "#8b5cf6",
        secondaryColor: "#ec4899",
        size: 48,
        opacity: 65,
    }),
    preset("geo-diamond-cyan", "Cyan Diamonds", {
        patternType: "diamonds",
        backgroundColor: "#083344",
        patternColor: "#22d3ee",
        secondaryColor: "#3b82f6",
        size: 44,
        opacity: 65,
    }),
    preset("geo-checker", "Classic Checker", {
        patternType: "checker",
        backgroundColor: "#18181b",
        patternColor: "#27272a",
        secondaryColor: "#52525b",
        size: 40,
        opacity: 100,
    }),
    preset("geo-checker-blue", "Blue Checker", {
        patternType: "checker",
        backgroundColor: "#172554",
        patternColor: "#1d4ed8",
        secondaryColor: "#60a5fa",
        size: 36,
        opacity: 75,
    }),
    preset("geo-triangle-purple", "Purple Triangles", {
        patternType: "triangles",
        backgroundColor: "#2e1065",
        patternColor: "#8b5cf6",
        secondaryColor: "#d946ef",
        size: 48,
        opacity: 75,
    }),
    preset("geo-triangle-cyan", "Cyan Triangles", {
        patternType: "triangles",
        backgroundColor: "#083344",
        patternColor: "#06b6d4",
        secondaryColor: "#22d3ee",
        size: 48,
        opacity: 70,
    }),
    preset("geo-rings", "Geometric Rings", {
        patternType: "rings",
        backgroundColor: "#020617",
        patternColor: "#6366f1",
        size: 46,
        thickness: 3,
        opacity: 70,
    }),
    preset("geo-cross", "Cross Matrix", {
        patternType: "crosshatch",
        backgroundColor: "#111827",
        patternColor: "#3b82f6",
        secondaryColor: "#8b5cf6",
        size: 42,
        thickness: 2,
        opacity: 55,
        angle: 45,
    }),
    preset("geo-weave", "Geometric Weave", {
        patternType: "weave",
        backgroundColor: "#18181b",
        patternColor: "#f43f5e",
        secondaryColor: "#8b5cf6",
        size: 40,
        thickness: 3,
        opacity: 60,
        angle: 45,
    }),
    preset("geo-diamond-gold", "Gold Diamonds", {
        patternType: "diamonds",
        backgroundColor: "#451a03",
        patternColor: "#f59e0b",
        secondaryColor: "#fde047",
        size: 50,
        opacity: 75,
    }),
    preset("geo-checker-pink", "Pink Checker", {
        patternType: "checker",
        backgroundColor: "#500724",
        patternColor: "#be185d",
        secondaryColor: "#f472b6",
        size: 42,
        opacity: 75,
    }),
    preset("geo-rings-green", "Emerald Rings", {
        patternType: "rings",
        backgroundColor: "#022c22",
        patternColor: "#34d399",
        size: 44,
        thickness: 3,
        opacity: 70,
    }),
];

const retroPresets: PatternPreset[] = [
    preset("retro-orange", "Retro Orange", {
        patternType: "waves",
        backgroundColor: "#431407",
        patternColor: "#f97316",
        secondaryColor: "#facc15",
        size: 64,
        opacity: 80,
    }),
    preset("retro-purple", "Retro Purple", {
        patternType: "waves",
        backgroundColor: "#2e1065",
        patternColor: "#a855f7",
        secondaryColor: "#f472b6",
        size: 64,
        opacity: 75,
    }),
    preset("retro-green", "Retro Green", {
        patternType: "waves",
        backgroundColor: "#14532d",
        patternColor: "#84cc16",
        secondaryColor: "#fde047",
        size: 58,
        opacity: 75,
    }),
    preset("retro-checker", "Retro Checker", {
        patternType: "checker",
        backgroundColor: "#7c2d12",
        patternColor: "#fb923c",
        secondaryColor: "#fde047",
        size: 42,
        opacity: 100,
    }),
    preset("retro-pink-checker", "Pink Checker", {
        patternType: "checker",
        backgroundColor: "#831843",
        patternColor: "#f472b6",
        secondaryColor: "#fbcfe8",
        size: 40,
        opacity: 95,
    }),
    preset("retro-lines", "Retro Lines", {
        patternType: "diagonal",
        backgroundColor: "#451a03",
        patternColor: "#fbbf24",
        size: 28,
        thickness: 5,
        opacity: 85,
        angle: 45,
    }),
    preset("retro-blue-lines", "Blue Lines", {
        patternType: "diagonal",
        backgroundColor: "#172554",
        patternColor: "#38bdf8",
        size: 26,
        thickness: 5,
        opacity: 80,
        angle: 135,
    }),
    preset("retro-rings", "Retro Rings", {
        patternType: "rings",
        backgroundColor: "#701a75",
        patternColor: "#f0abfc",
        size: 50,
        thickness: 5,
        opacity: 75,
    }),
    preset("retro-triangles", "Retro Triangles", {
        patternType: "triangles",
        backgroundColor: "#422006",
        patternColor: "#facc15",
        secondaryColor: "#f97316",
        size: 56,
        opacity: 90,
    }),
    preset("retro-weave", "Retro Weave", {
        patternType: "weave",
        backgroundColor: "#4c0519",
        patternColor: "#fb7185",
        secondaryColor: "#fdba74",
        size: 44,
        thickness: 4,
        opacity: 75,
        angle: 45,
    }),
    preset("retro-aqua", "Retro Aqua", {
        patternType: "waves",
        backgroundColor: "#134e4a",
        patternColor: "#2dd4bf",
        secondaryColor: "#fde047",
        size: 60,
        opacity: 80,
    }),
    preset("retro-disco", "Disco", {
        patternType: "diamonds",
        backgroundColor: "#1e1b4b",
        patternColor: "#ec4899",
        secondaryColor: "#22d3ee",
        size: 42,
        opacity: 90,
    }),
];

const techPresets: PatternPreset[] = [
    preset("tech-matrix", "Matrix", {
        patternType: "grid",
        backgroundColor: "#020617",
        patternColor: "#22c55e",
        size: 20,
        thickness: 1,
        opacity: 45,
    }),
    preset("tech-cyber-grid", "Cyber Grid", {
        patternType: "grid",
        backgroundColor: "#020617",
        patternColor: "#06b6d4",
        size: 26,
        thickness: 1,
        opacity: 55,
    }),
    preset("tech-purple-grid", "Quantum Grid", {
        patternType: "grid",
        backgroundColor: "#09090b",
        patternColor: "#8b5cf6",
        size: 28,
        thickness: 1,
        opacity: 55,
    }),
    preset("tech-crosshair", "Crosshair", {
        patternType: "crosshatch",
        backgroundColor: "#020617",
        patternColor: "#06b6d4",
        secondaryColor: "#6366f1",
        size: 32,
        thickness: 1,
        opacity: 50,
        angle: 45,
    }),
    preset("tech-circuit", "Circuit", {
        patternType: "weave",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        secondaryColor: "#8b5cf6",
        size: 36,
        thickness: 2,
        opacity: 55,
        angle: 90,
    }),
    preset("tech-scan", "Scan Lines", {
        patternType: "horizontal",
        backgroundColor: "#020617",
        patternColor: "#38bdf8",
        size: 8,
        thickness: 1,
        opacity: 30,
    }),
    preset("tech-terminal", "Terminal", {
        patternType: "horizontal",
        backgroundColor: "#052e16",
        patternColor: "#22c55e",
        size: 10,
        thickness: 1,
        opacity: 35,
    }),
    preset("tech-dots", "Data Points", {
        patternType: "dots",
        backgroundColor: "#020617",
        patternColor: "#22d3ee",
        size: 18,
        thickness: 1,
        opacity: 65,
    }),
    preset("tech-radar", "Radar", {
        patternType: "rings",
        backgroundColor: "#022c22",
        patternColor: "#34d399",
        size: 52,
        thickness: 2,
        opacity: 55,
    }),
    preset("tech-purple-radar", "Purple Radar", {
        patternType: "rings",
        backgroundColor: "#1e1b4b",
        patternColor: "#818cf8",
        size: 52,
        thickness: 2,
        opacity: 60,
    }),
    preset("tech-diagonal", "Data Flow", {
        patternType: "diagonal",
        backgroundColor: "#020617",
        patternColor: "#3b82f6",
        size: 24,
        thickness: 2,
        opacity: 45,
        angle: 120,
    }),
    preset("tech-neon", "Neon Mesh", {
        patternType: "crosshatch",
        backgroundColor: "#09090b",
        patternColor: "#ec4899",
        secondaryColor: "#22d3ee",
        size: 38,
        thickness: 1,
        opacity: 65,
        angle: 60,
    }),
];

const darkPresets: PatternPreset[] = [
    preset("dark-carbon", "Carbon", {
        patternType: "weave",
        backgroundColor: "#09090b",
        patternColor: "#27272a",
        secondaryColor: "#52525b",
        size: 24,
        thickness: 3,
        opacity: 70,
        angle: 45,
    }),
    preset("dark-grid", "Dark Grid", {
        patternType: "grid",
        backgroundColor: "#09090b",
        patternColor: "#3f3f46",
        size: 32,
        thickness: 1,
        opacity: 50,
    }),
    preset("dark-dots", "Dark Dots", {
        patternType: "dots",
        backgroundColor: "#09090b",
        patternColor: "#71717a",
        size: 26,
        thickness: 1,
        opacity: 50,
    }),
    preset("dark-rings", "Dark Rings", {
        patternType: "rings",
        backgroundColor: "#09090b",
        patternColor: "#52525b",
        size: 42,
        thickness: 2,
        opacity: 55,
    }),
    preset("dark-purple", "Dark Purple", {
        patternType: "crosshatch",
        backgroundColor: "#09090b",
        patternColor: "#581c87",
        secondaryColor: "#312e81",
        size: 44,
        thickness: 2,
        opacity: 60,
        angle: 45,
    }),
    preset("dark-blue", "Dark Blue", {
        patternType: "grid",
        backgroundColor: "#020617",
        patternColor: "#1e40af",
        size: 32,
        thickness: 1,
        opacity: 48,
    }),
    preset("dark-red", "Dark Red", {
        patternType: "diagonal",
        backgroundColor: "#09090b",
        patternColor: "#7f1d1d",
        size: 30,
        thickness: 3,
        opacity: 55,
        angle: 135,
    }),
    preset("dark-emerald", "Dark Emerald", {
        patternType: "diamonds",
        backgroundColor: "#09090b",
        patternColor: "#064e3b",
        secondaryColor: "#047857",
        size: 44,
        opacity: 60,
    }),
    preset("dark-checker", "Black Checker", {
        patternType: "checker",
        backgroundColor: "#09090b",
        patternColor: "#18181b",
        secondaryColor: "#27272a",
        size: 36,
        opacity: 100,
    }),
    preset("dark-waves", "Dark Waves", {
        patternType: "waves",
        backgroundColor: "#09090b",
        patternColor: "#3f3f46",
        secondaryColor: "#52525b",
        size: 56,
        opacity: 65,
    }),
    preset("dark-steel", "Dark Steel", {
        patternType: "horizontal",
        backgroundColor: "#18181b",
        patternColor: "#52525b",
        size: 12,
        thickness: 1,
        opacity: 40,
    }),
    preset("dark-obsidian", "Obsidian", {
        patternType: "diamonds",
        backgroundColor: "#000000",
        patternColor: "#27272a",
        secondaryColor: "#18181b",
        size: 48,
        opacity: 70,
    }),
];

const pastelPresets: PatternPreset[] = [
    preset("pastel-pink-dots", "Pink Dots", {
        patternType: "dots",
        backgroundColor: "#fce7f3",
        patternColor: "#f472b6",
        size: 28,
        thickness: 2,
        opacity: 45,
    }),
    preset("pastel-blue-dots", "Blue Dots", {
        patternType: "dots",
        backgroundColor: "#e0f2fe",
        patternColor: "#38bdf8",
        size: 28,
        thickness: 2,
        opacity: 40,
    }),
    preset("pastel-mint-grid", "Mint Grid", {
        patternType: "grid",
        backgroundColor: "#d1fae5",
        patternColor: "#34d399",
        size: 32,
        thickness: 1,
        opacity: 35,
    }),
    preset("pastel-lavender-grid", "Lavender Grid", {
        patternType: "grid",
        backgroundColor: "#ede9fe",
        patternColor: "#a78bfa",
        size: 32,
        thickness: 1,
        opacity: 35,
    }),
    preset("pastel-candy", "Candy Checker", {
        patternType: "checker",
        backgroundColor: "#fce7f3",
        patternColor: "#f9a8d4",
        secondaryColor: "#c4b5fd",
        size: 44,
        opacity: 65,
    }),
    preset("pastel-mint-checker", "Mint Checker", {
        patternType: "checker",
        backgroundColor: "#ecfccb",
        patternColor: "#a7f3d0",
        secondaryColor: "#bae6fd",
        size: 42,
        opacity: 60,
    }),
    preset("pastel-rings", "Lavender Rings", {
        patternType: "rings",
        backgroundColor: "#f3e8ff",
        patternColor: "#c084fc",
        size: 48,
        thickness: 3,
        opacity: 40,
    }),
    preset("pastel-waves", "Pastel Waves", {
        patternType: "waves",
        backgroundColor: "#fce7f3",
        patternColor: "#f9a8d4",
        secondaryColor: "#7dd3fc",
        size: 60,
        opacity: 50,
    }),
    preset("pastel-diamond", "Pastel Diamond", {
        patternType: "diamonds",
        backgroundColor: "#faf5ff",
        patternColor: "#d8b4fe",
        secondaryColor: "#f9a8d4",
        size: 48,
        opacity: 48,
    }),
    preset("pastel-peach", "Peach Lines", {
        patternType: "diagonal",
        backgroundColor: "#fff7ed",
        patternColor: "#fdba74",
        size: 28,
        thickness: 2,
        opacity: 40,
        angle: 45,
    }),
    preset("pastel-sky", "Sky Lines", {
        patternType: "horizontal",
        backgroundColor: "#f0f9ff",
        patternColor: "#7dd3fc",
        size: 24,
        thickness: 1,
        opacity: 38,
    }),
    preset("pastel-spring", "Spring Weave", {
        patternType: "weave",
        backgroundColor: "#f0fdf4",
        patternColor: "#86efac",
        secondaryColor: "#bae6fd",
        size: 40,
        thickness: 2,
        opacity: 42,
        angle: 45,
    }),
];

export const patternPresetCategories: PatternPresetCategory[] = [
    {
        id: "minimal",
        name: "Minimal",
        presets: minimalPresets,
    },
    {
        id: "grid",
        name: "Grid",
        presets: gridPresets,
    },
    {
        id: "dots",
        name: "Dots",
        presets: dotsPresets,
    },
    {
        id: "geometric",
        name: "Geometric",
        presets: geometricPresets,
    },
    {
        id: "retro",
        name: "Retro",
        presets: retroPresets,
    },
    {
        id: "tech",
        name: "Tech",
        presets: techPresets,
    },
    {
        id: "dark",
        name: "Dark",
        presets: darkPresets,
    },
    {
        id: "pastel",
        name: "Pastel",
        presets: pastelPresets,
    },
];
