import type { ClipPathPresetPoint } from "./clip-path.type";

export interface ClipPathPreset {
    id: string;
    name: string;
    points: ClipPathPresetPoint[];
}

export interface ClipPathPresetCategory {
    id: string;
    name: string;
    presets: ClipPathPreset[];
}

export const clipPathPresetCategories: ClipPathPresetCategory[] = [
    {
        id: "basic",
        name: "Basic shapes",
        presets: [
            {
                id: "triangle-up",
                name: "Triangle up",
                points: [
                    { x: 50, y: 3 },
                    { x: 97, y: 97 },
                    { x: 3, y: 97 },
                ],
            },
            {
                id: "triangle-down",
                name: "Triangle down",
                points: [
                    { x: 3, y: 3 },
                    { x: 97, y: 3 },
                    { x: 50, y: 97 },
                ],
            },
            {
                id: "triangle-left",
                name: "Triangle left",
                points: [
                    { x: 3, y: 50 },
                    { x: 97, y: 3 },
                    { x: 97, y: 97 },
                ],
            },
            {
                id: "triangle-right",
                name: "Triangle right",
                points: [
                    { x: 3, y: 3 },
                    { x: 97, y: 50 },
                    { x: 3, y: 97 },
                ],
            },
            {
                id: "diamond",
                name: "Diamond",
                points: [
                    { x: 50, y: 2 },
                    { x: 98, y: 50 },
                    { x: 50, y: 98 },
                    { x: 2, y: 50 },
                ],
            },
            {
                id: "pentagon",
                name: "Pentagon",
                points: [
                    { x: 50, y: 2 },
                    { x: 98, y: 38 },
                    { x: 80, y: 96 },
                    { x: 20, y: 96 },
                    { x: 2, y: 38 },
                ],
            },
            {
                id: "hexagon",
                name: "Hexagon",
                points: [
                    { x: 25, y: 3 },
                    { x: 75, y: 3 },
                    { x: 98, y: 50 },
                    { x: 75, y: 97 },
                    { x: 25, y: 97 },
                    { x: 2, y: 50 },
                ],
            },
            {
                id: "octagon",
                name: "Octagon",
                points: [
                    { x: 30, y: 2 },
                    { x: 70, y: 2 },
                    { x: 98, y: 30 },
                    { x: 98, y: 70 },
                    { x: 70, y: 98 },
                    { x: 30, y: 98 },
                    { x: 2, y: 70 },
                    { x: 2, y: 30 },
                ],
            },
            {
                id: "trapezoid",
                name: "Trapezoid",
                points: [
                    { x: 20, y: 5 },
                    { x: 80, y: 5 },
                    { x: 100, y: 95 },
                    { x: 0, y: 95 },
                ],
            },
            {
                id: "parallelogram",
                name: "Parallelogram",
                points: [
                    { x: 20, y: 5 },
                    { x: 100, y: 5 },
                    { x: 80, y: 95 },
                    { x: 0, y: 95 },
                ],
            },
            {
                id: "rhombus",
                name: "Rhombus",
                points: [
                    { x: 25, y: 50 },
                    { x: 50, y: 5 },
                    { x: 75, y: 50 },
                    { x: 50, y: 95 },
                ],
            },
            {
                id: "bevel",
                name: "Bevel",
                points: [
                    { x: 12, y: 0 },
                    { x: 88, y: 0 },
                    { x: 100, y: 12 },
                    { x: 100, y: 88 },
                    { x: 88, y: 100 },
                    { x: 12, y: 100 },
                    { x: 0, y: 88 },
                    { x: 0, y: 12 },
                ],
            },
        ],
    },
    {
        id: "arrows",
        name: "Arrows & direction",
        presets: [
            {
                id: "arrow-right",
                name: "Arrow right",
                points: [
                    { x: 5, y: 32 },
                    { x: 60, y: 32 },
                    { x: 60, y: 10 },
                    { x: 96, y: 50 },
                    { x: 60, y: 90 },
                    { x: 60, y: 68 },
                    { x: 5, y: 68 },
                ],
            },
            {
                id: "arrow-left",
                name: "Arrow left",
                points: [
                    { x: 95, y: 32 },
                    { x: 40, y: 32 },
                    { x: 40, y: 10 },
                    { x: 4, y: 50 },
                    { x: 40, y: 90 },
                    { x: 40, y: 68 },
                    { x: 95, y: 68 },
                ],
            },
            {
                id: "arrow-up",
                name: "Arrow up",
                points: [
                    { x: 32, y: 95 },
                    { x: 32, y: 40 },
                    { x: 10, y: 40 },
                    { x: 50, y: 4 },
                    { x: 90, y: 40 },
                    { x: 68, y: 40 },
                    { x: 68, y: 95 },
                ],
            },
            {
                id: "arrow-down",
                name: "Arrow down",
                points: [
                    { x: 32, y: 5 },
                    { x: 68, y: 5 },
                    { x: 68, y: 60 },
                    { x: 90, y: 60 },
                    { x: 50, y: 96 },
                    { x: 10, y: 60 },
                    { x: 32, y: 60 },
                ],
            },
            {
                id: "chevron-right",
                name: "Chevron right",
                points: [
                    { x: 20, y: 5 },
                    { x: 50, y: 5 },
                    { x: 90, y: 50 },
                    { x: 50, y: 95 },
                    { x: 20, y: 95 },
                    { x: 60, y: 50 },
                ],
            },
            {
                id: "chevron-left",
                name: "Chevron left",
                points: [
                    { x: 80, y: 5 },
                    { x: 50, y: 5 },
                    { x: 10, y: 50 },
                    { x: 50, y: 95 },
                    { x: 80, y: 95 },
                    { x: 40, y: 50 },
                ],
            },
            {
                id: "double-arrow-horizontal",
                name: "Horizontal",
                points: [
                    { x: 0, y: 50 },
                    { x: 25, y: 20 },
                    { x: 25, y: 38 },
                    { x: 75, y: 38 },
                    { x: 75, y: 20 },
                    { x: 100, y: 50 },
                    { x: 75, y: 80 },
                    { x: 75, y: 62 },
                    { x: 25, y: 62 },
                    { x: 25, y: 80 },
                ],
            },
            {
                id: "double-arrow-vertical",
                name: "Vertical",
                points: [
                    { x: 50, y: 0 },
                    { x: 80, y: 25 },
                    { x: 62, y: 25 },
                    { x: 62, y: 75 },
                    { x: 80, y: 75 },
                    { x: 50, y: 100 },
                    { x: 20, y: 75 },
                    { x: 38, y: 75 },
                    { x: 38, y: 25 },
                    { x: 20, y: 25 },
                ],
            },
        ],
    },
    {
        id: "interface",
        name: "Interface",
        presets: [
            {
                id: "heart",
                name: "Heart",
                points: [
                    { x: 50, y: 92 },
                    { x: 42, y: 84 },
                    { x: 32, y: 75 },
                    { x: 22, y: 65 },
                    { x: 13, y: 54 },
                    { x: 7, y: 43 },
                    { x: 6, y: 32 },
                    { x: 10, y: 22 },
                    { x: 18, y: 15 },
                    { x: 28, y: 13 },
                    { x: 38, y: 17 },
                    { x: 45, y: 25 },
                    { x: 50, y: 34 },
                    { x: 55, y: 25 },
                    { x: 62, y: 17 },
                    { x: 72, y: 13 },
                    { x: 82, y: 15 },
                    { x: 90, y: 22 },
                    { x: 94, y: 32 },
                    { x: 93, y: 43 },
                    { x: 87, y: 54 },
                    { x: 78, y: 65 },
                    { x: 68, y: 75 },
                    { x: 58, y: 84 },
                ],
            },
            {
                id: "message",
                name: "Message",
                points: [
                    { x: 8, y: 12 },
                    { x: 92, y: 12 },
                    { x: 96, y: 17 },
                    { x: 96, y: 68 },
                    { x: 91, y: 74 },
                    { x: 58, y: 74 },
                    { x: 35, y: 94 },
                    { x: 40, y: 74 },
                    { x: 9, y: 74 },
                    { x: 4, y: 68 },
                    { x: 4, y: 18 },
                ],
            },
            {
                id: "message-left",
                name: "Message left",
                points: [
                    { x: 7, y: 10 },
                    { x: 93, y: 10 },
                    { x: 97, y: 15 },
                    { x: 97, y: 70 },
                    { x: 92, y: 76 },
                    { x: 28, y: 76 },
                    { x: 8, y: 95 },
                    { x: 14, y: 76 },
                    { x: 7, y: 76 },
                    { x: 3, y: 70 },
                    { x: 3, y: 16 },
                ],
            },
            {
                id: "bookmark",
                name: "Bookmark",
                points: [
                    { x: 20, y: 4 },
                    { x: 80, y: 4 },
                    { x: 80, y: 96 },
                    { x: 50, y: 75 },
                    { x: 20, y: 96 },
                ],
            },
            {
                id: "tag",
                name: "Tag",
                points: [
                    { x: 5, y: 30 },
                    { x: 30, y: 5 },
                    { x: 95, y: 5 },
                    { x: 95, y: 70 },
                    { x: 70, y: 95 },
                    { x: 5, y: 95 },
                ],
            },
            {
                id: "play",
                name: "Play",
                points: [
                    { x: 18, y: 5 },
                    { x: 95, y: 50 },
                    { x: 18, y: 95 },
                ],
            },
            {
                id: "pause",
                name: "Pause",
                points: [
                    { x: 15, y: 5 },
                    { x: 42, y: 5 },
                    { x: 42, y: 95 },
                    { x: 15, y: 95 },
                    { x: 15, y: 5 },
                    { x: 58, y: 5 },
                    { x: 85, y: 5 },
                    { x: 85, y: 95 },
                    { x: 58, y: 95 },
                ],
            },
            {
                id: "home",
                name: "Home",
                points: [
                    { x: 5, y: 45 },
                    { x: 50, y: 5 },
                    { x: 95, y: 45 },
                    { x: 82, y: 45 },
                    { x: 82, y: 95 },
                    { x: 60, y: 95 },
                    { x: 60, y: 66 },
                    { x: 40, y: 66 },
                    { x: 40, y: 95 },
                    { x: 18, y: 95 },
                    { x: 18, y: 45 },
                ],
            },
            {
                id: "shield",
                name: "Shield",
                points: [
                    { x: 50, y: 3 },
                    { x: 90, y: 18 },
                    { x: 86, y: 60 },
                    { x: 72, y: 82 },
                    { x: 50, y: 97 },
                    { x: 28, y: 82 },
                    { x: 14, y: 60 },
                    { x: 10, y: 18 },
                ],
            },
            {
                id: "like",
                name: "Like",
                points: [
                    { x: 6, y: 42 },
                    { x: 27, y: 42 },
                    { x: 27, y: 88 },
                    { x: 6, y: 88 },
                    { x: 6, y: 42 },
                    { x: 32, y: 42 },
                    { x: 43, y: 30 },
                    { x: 52, y: 10 },
                    { x: 61, y: 10 },
                    { x: 66, y: 17 },
                    { x: 62, y: 36 },
                    { x: 87, y: 36 },
                    { x: 94, y: 43 },
                    { x: 83, y: 82 },
                    { x: 76, y: 88 },
                    { x: 32, y: 88 },
                ],
            },
        ],
    },
    {
        id: "symbols",
        name: "Symbols",
        presets: [
            {
                id: "plus",
                name: "Plus",
                points: [
                    { x: 35, y: 4 },
                    { x: 65, y: 4 },
                    { x: 65, y: 35 },
                    { x: 96, y: 35 },
                    { x: 96, y: 65 },
                    { x: 65, y: 65 },
                    { x: 65, y: 96 },
                    { x: 35, y: 96 },
                    { x: 35, y: 65 },
                    { x: 4, y: 65 },
                    { x: 4, y: 35 },
                    { x: 35, y: 35 },
                ],
            },
            {
                id: "x",
                name: "Close",
                points: [
                    { x: 18, y: 5 },
                    { x: 50, y: 37 },
                    { x: 82, y: 5 },
                    { x: 95, y: 18 },
                    { x: 63, y: 50 },
                    { x: 95, y: 82 },
                    { x: 82, y: 95 },
                    { x: 50, y: 63 },
                    { x: 18, y: 95 },
                    { x: 5, y: 82 },
                    { x: 37, y: 50 },
                    { x: 5, y: 18 },
                ],
            },
            {
                id: "check",
                name: "Check",
                points: [
                    { x: 4, y: 52 },
                    { x: 20, y: 36 },
                    { x: 42, y: 58 },
                    { x: 80, y: 18 },
                    { x: 96, y: 34 },
                    { x: 42, y: 90 },
                ],
            },
            {
                id: "star",
                name: "Star",
                points: [
                    { x: 50, y: 2 },
                    { x: 61, y: 36 },
                    { x: 97, y: 36 },
                    { x: 68, y: 57 },
                    { x: 79, y: 94 },
                    { x: 50, y: 72 },
                    { x: 21, y: 94 },
                    { x: 32, y: 57 },
                    { x: 3, y: 36 },
                    { x: 39, y: 36 },
                ],
            },
            {
                id: "bolt",
                name: "Bolt",
                points: [
                    { x: 54, y: 2 },
                    { x: 20, y: 53 },
                    { x: 46, y: 53 },
                    { x: 37, y: 98 },
                    { x: 82, y: 39 },
                    { x: 55, y: 39 },
                ],
            },
            {
                id: "hourglass",
                name: "Hourglass",
                points: [
                    { x: 15, y: 5 },
                    { x: 85, y: 5 },
                    { x: 65, y: 50 },
                    { x: 85, y: 95 },
                    { x: 15, y: 95 },
                    { x: 35, y: 50 },
                ],
            },
        ],
    },
    {
        id: "decorative",
        name: "Decorative",
        presets: [
            {
                id: "burst",
                name: "Burst",
                points: [
                    { x: 50, y: 2 },
                    { x: 61, y: 20 },
                    { x: 81, y: 10 },
                    { x: 80, y: 32 },
                    { x: 98, y: 40 },
                    { x: 83, y: 55 },
                    { x: 94, y: 75 },
                    { x: 71, y: 76 },
                    { x: 62, y: 97 },
                    { x: 48, y: 80 },
                    { x: 28, y: 94 },
                    { x: 27, y: 71 },
                    { x: 5, y: 64 },
                    { x: 21, y: 47 },
                    { x: 5, y: 31 },
                    { x: 29, y: 29 },
                ],
            },
            {
                id: "ticket",
                name: "Ticket",
                points: [
                    { x: 0, y: 10 },
                    { x: 10, y: 10 },
                    { x: 14, y: 20 },
                    { x: 10, y: 30 },
                    { x: 0, y: 30 },
                    { x: 0, y: 70 },
                    { x: 10, y: 70 },
                    { x: 14, y: 80 },
                    { x: 10, y: 90 },
                    { x: 0, y: 90 },
                    { x: 0, y: 100 },
                    { x: 100, y: 100 },
                    { x: 100, y: 90 },
                    { x: 90, y: 90 },
                    { x: 86, y: 80 },
                    { x: 90, y: 70 },
                    { x: 100, y: 70 },
                    { x: 100, y: 30 },
                    { x: 90, y: 30 },
                    { x: 86, y: 20 },
                    { x: 90, y: 10 },
                    { x: 100, y: 10 },
                    { x: 100, y: 0 },
                    { x: 0, y: 0 },
                ],
            },
            {
                id: "ribbon-left",
                name: "Ribbon left",
                points: [
                    { x: 0, y: 15 },
                    { x: 100, y: 15 },
                    { x: 100, y: 85 },
                    { x: 0, y: 85 },
                    { x: 20, y: 50 },
                ],
            },
            {
                id: "ribbon-right",
                name: "Ribbon right",
                points: [
                    { x: 0, y: 15 },
                    { x: 100, y: 15 },
                    { x: 80, y: 50 },
                    { x: 100, y: 85 },
                    { x: 0, y: 85 },
                ],
            },
            {
                id: "frame-cut",
                name: "Cut corners",
                points: [
                    { x: 12, y: 0 },
                    { x: 88, y: 0 },
                    { x: 100, y: 12 },
                    { x: 100, y: 88 },
                    { x: 88, y: 100 },
                    { x: 12, y: 100 },
                    { x: 0, y: 88 },
                    { x: 0, y: 12 },
                ],
            },
            {
                id: "slant",
                name: "Slant",
                points: [
                    { x: 0, y: 15 },
                    { x: 100, y: 0 },
                    { x: 100, y: 85 },
                    { x: 0, y: 100 },
                ],
            },
            {
                id: "wave-block",
                name: "Wave",
                points: [
                    { x: 0, y: 10 },
                    { x: 20, y: 4 },
                    { x: 40, y: 12 },
                    { x: 60, y: 4 },
                    { x: 80, y: 12 },
                    { x: 100, y: 6 },
                    { x: 100, y: 90 },
                    { x: 80, y: 96 },
                    { x: 60, y: 88 },
                    { x: 40, y: 96 },
                    { x: 20, y: 88 },
                    { x: 0, y: 94 },
                ],
            },
        ],
    },
];

export const clipPathPresets = clipPathPresetCategories.flatMap(
    (category) => category.presets,
);
