import type { ClipPathPresetPoint } from "./clip-path.type";

export interface ClipPathPreset {
    id: string;
    name: string;
    points: ClipPathPresetPoint[];
}

export interface ClipPathPresetCategory {
    id: string;
    name: string;
    presets: ClipPathPreset[];
}

export const clipPathPresetCategories: ClipPathPresetCategory[] = [
    {
        id: "basic",
        name: "Basic shapes",
        presets: [
            {
                id: "triangle-up",
                name: "Triangle up",
                points: [
                    { x: 50, y: 3 },
                    { x: 97, y: 97 },
                    { x: 3, y: 97 },
                ],
            },
            {
                id: "triangle-down",
                name: "Triangle down",
                points: [
                    { x: 3, y: 3 },
                    { x: 97, y: 3 },
                    { x: 50, y: 97 },
                ],
            },
            {
                id: "triangle-left",
                name: "Triangle left",
                points: [
                    { x: 3, y: 50 },
                    { x: 97, y: 3 },
                    { x: 97, y: 97 },
                ],
            },
            {
                id: "triangle-right",
                name: "Triangle right",
                points: [
                    { x: 3, y: 3 },
                    { x: 97, y: 50 },
                    { x: 3, y: 97 },
                ],
            },
            {
                id: "diamond",
                name: "Diamond",
                points: [
                    { x: 50, y: 2 },
                    { x: 98, y: 50 },
                    { x: 50, y: 98 },
                    { x: 2, y: 50 },
                ],
            },
            {
                id: "pentagon",
                name: "Pentagon",
                points: [
                    { x: 50, y: 2 },
                    { x: 98, y: 38 },
                    { x: 80, y: 96 },
                    { x: 20, y: 96 },
                    { x: 2, y: 38 },
                ],
            },
            {
                id: "hexagon",
                name: "Hexagon",
                points: [
                    { x: 25, y: 3 },
                    { x: 75, y: 3 },
                    { x: 98, y: 50 },
                    { x: 75, y: 97 },
                    { x: 25, y: 97 },
                    { x: 2, y: 50 },
                ],
            },
            {
                id: "octagon",
                name: "Octagon",
                points: [
                    { x: 30, y: 2 },
                    { x: 70, y: 2 },
                    { x: 98, y: 30 },
                    { x: 98, y: 70 },
                    { x: 70, y: 98 },
                    { x: 30, y: 98 },
                    { x: 2, y: 70 },
                    { x: 2, y: 30 },
                ],
            },
            {
                id: "trapezoid",
                name: "Trapezoid",
                points: [
                    { x: 20, y: 5 },
                    { x: 80, y: 5 },
                    { x: 100, y: 95 },
                    { x: 0, y: 95 },
                ],
            },
            {
                id: "parallelogram",
                name: "Parallelogram",
                points: [
                    { x: 20, y: 5 },
                    { x: 100, y: 5 },
                    { x: 80, y: 95 },
                    { x: 0, y: 95 },
                ],
            },
            {
                id: "rhombus",
                name: "Rhombus",
                points: [
                    { x: 25, y: 50 },
                    { x: 50, y: 5 },
                    { x: 75, y: 50 },
                    { x: 50, y: 95 },
                ],
            },
            {
                id: "bevel",
                name: "Bevel",
                points: [
                    { x: 12, y: 0 },
                    { x: 88, y: 0 },
                    { x: 100, y: 12 },
                    { x: 100, y: 88 },
                    { x: 88, y: 100 },
                    { x: 12, y: 100 },
                    { x: 0, y: 88 },
                    { x: 0, y: 12 },
                ],
            },
        ],
    },
    {
        id: "arrows",
        name: "Arrows & direction",
        presets: [
            {
                id: "arrow-right",
                name: "Arrow right",
                points: [
                    { x: 5, y: 32 },
                    { x: 60, y: 32 },
                    { x: 60, y: 10 },
                    { x: 96, y: 50 },
                    { x: 60, y: 90 },
                    { x: 60, y: 68 },
                    { x: 5, y: 68 },
                ],
            },
            {
                id: "arrow-left",
                name: "Arrow left",
                points: [
                    { x: 95, y: 32 },
                    { x: 40, y: 32 },
                    { x: 40, y: 10 },
                    { x: 4, y: 50 },
                    { x: 40, y: 90 },
                    { x: 40, y: 68 },
                    { x: 95, y: 68 },
                ],
            },
            {
                id: "arrow-up",
                name: "Arrow up",
                points: [
                    { x: 32, y: 95 },
                    { x: 32, y: 40 },
                    { x: 10, y: 40 },
                    { x: 50, y: 4 },
                    { x: 90, y: 40 },
                    { x: 68, y: 40 },
                    { x: 68, y: 95 },
                ],
            },
            {
                id: "arrow-down",
                name: "Arrow down",
                points: [
                    { x: 32, y: 5 },
                    { x: 68, y: 5 },
                    { x: 68, y: 60 },
                    { x: 90, y: 60 },
                    { x: 50, y: 96 },
                    { x: 10, y: 60 },
                    { x: 32, y: 60 },
                ],
            },
            {
                id: "chevron-right",
                name: "Chevron right",
                points: [
                    { x: 20, y: 5 },
                    { x: 50, y: 5 },
                    { x: 90, y: 50 },
                    { x: 50, y: 95 },
                    { x: 20, y: 95 },
                    { x: 60, y: 50 },
                ],
            },
            {
                id: "chevron-left",
                name: "Chevron left",
                points: [
                    { x: 80, y: 5 },
                    { x: 50, y: 5 },
                    { x: 10, y: 50 },
                    { x: 50, y: 95 },
                    { x: 80, y: 95 },
                    { x: 40, y: 50 },
                ],
            },
            {
                id: "double-arrow-horizontal",
                name: "Horizontal",
                points: [
                    { x: 0, y: 50 },
                    { x: 25, y: 20 },
                    { x: 25, y: 38 },
                    { x: 75, y: 38 },
                    { x: 75, y: 20 },
                    { x: 100, y: 50 },
                    { x: 75, y: 80 },
                    { x: 75, y: 62 },
                    { x: 25, y: 62 },
                    { x: 25, y: 80 },
                ],
            },
            {
                id: "double-arrow-vertical",
                name: "Vertical",
                points: [
                    { x: 50, y: 0 },
                    { x: 80, y: 25 },
                    { x: 62, y: 25 },
                    { x: 62, y: 75 },
                    { x: 80, y: 75 },
                    { x: 50, y: 100 },
                    { x: 20, y: 75 },
                    { x: 38, y: 75 },
                    { x: 38, y: 25 },
                    { x: 20, y: 25 },
                ],
            },
        ],
    },
    {
        id: "interface",
        name: "Interface",
        presets: [
            {
                id: "heart",
                name: "Heart",
                points: [
                    { x: 50, y: 92 },
                    { x: 42, y: 84 },
                    { x: 32, y: 75 },
                    { x: 22, y: 65 },
                    { x: 13, y: 54 },
                    { x: 7, y: 43 },
                    { x: 6, y: 32 },
                    { x: 10, y: 22 },
                    { x: 18, y: 15 },
                    { x: 28, y: 13 },
                    { x: 38, y: 17 },
                    { x: 45, y: 25 },
                    { x: 50, y: 34 },
                    { x: 55, y: 25 },
                    { x: 62, y: 17 },
                    { x: 72, y: 13 },
                    { x: 82, y: 15 },
                    { x: 90, y: 22 },
                    { x: 94, y: 32 },
                    { x: 93, y: 43 },
                    { x: 87, y: 54 },
                    { x: 78, y: 65 },
                    { x: 68, y: 75 },
                    { x: 58, y: 84 },
                ],
            },
            {
                id: "message",
                name: "Message",
                points: [
                    { x: 8, y: 12 },
                    { x: 92, y: 12 },
                    { x: 96, y: 17 },
                    { x: 96, y: 68 },
                    { x: 91, y: 74 },
                    { x: 58, y: 74 },
                    { x: 35, y: 94 },
                    { x: 40, y: 74 },
                    { x: 9, y: 74 },
                    { x: 4, y: 68 },
                    { x: 4, y: 18 },
                ],
            },
            {
                id: "bookmark",
                name: "Bookmark",
                points: [
                    { x: 20, y: 4 },
                    { x: 80, y: 4 },
                    { x: 80, y: 96 },
                    { x: 50, y: 75 },
                    { x: 20, y: 96 },
                ],
            },
            {
                id: "tag",
                name: "Tag",
                points: [
                    { x: 5, y: 30 },
                    { x: 30, y: 5 },
                    { x: 95, y: 5 },
                    { x: 95, y: 70 },
                    { x: 70, y: 95 },
                    { x: 5, y: 95 },
                ],
            },
            {
                id: "play",
                name: "Play",
                points: [
                    { x: 18, y: 5 },
                    { x: 95, y: 50 },
                    { x: 18, y: 95 },
                ],
            },
            {
                id: "home",
                name: "Home",
                points: [
                    { x: 5, y: 45 },
                    { x: 50, y: 5 },
                    { x: 95, y: 45 },
                    { x: 82, y: 45 },
                    { x: 82, y: 95 },
                    { x: 60, y: 95 },
                    { x: 60, y: 66 },
                    { x: 40, y: 66 },
                    { x: 40, y: 95 },
                    { x: 18, y: 95 },
                    { x: 18, y: 45 },
                ],
            },
            {
                id: "shield",
                name: "Shield",
                points: [
                    { x: 50, y: 3 },
                    { x: 90, y: 18 },
                    { x: 86, y: 60 },
                    { x: 72, y: 82 },
                    { x: 50, y: 97 },
                    { x: 28, y: 82 },
                    { x: 14, y: 60 },
                    { x: 10, y: 18 },
                ],
            },
            {
                id: "like",
                name: "Like",
                points: [
                    { x: 6, y: 42 },
                    { x: 27, y: 42 },
                    { x: 27, y: 88 },
                    { x: 6, y: 88 },
                    { x: 6, y: 42 },
                    { x: 32, y: 42 },
                    { x: 43, y: 30 },
                    { x: 52, y: 10 },
                    { x: 61, y: 10 },
                    { x: 66, y: 17 },
                    { x: 62, y: 36 },
                    { x: 87, y: 36 },
                    { x: 94, y: 43 },
                    { x: 83, y: 82 },
                    { x: 76, y: 88 },
                    { x: 32, y: 88 },
                ],
            },
        ],
    },
    {
        id: "symbols",
        name: "Symbols",
        presets: [
            {
                id: "plus",
                name: "Plus",
                points: [
                    { x: 35, y: 4 },
                    { x: 65, y: 4 },
                    { x: 65, y: 35 },
                    { x: 96, y: 35 },
                    { x: 96, y: 65 },
                    { x: 65, y: 65 },
                    { x: 65, y: 96 },
                    { x: 35, y: 96 },
                    { x: 35, y: 65 },
                    { x: 4, y: 65 },
                    { x: 4, y: 35 },
                    { x: 35, y: 35 },
                ],
            },
            {
                id: "x",
                name: "Close",
                points: [
                    { x: 18, y: 5 },
                    { x: 50, y: 37 },
                    { x: 82, y: 5 },
                    { x: 95, y: 18 },
                    { x: 63, y: 50 },
                    { x: 95, y: 82 },
                    { x: 82, y: 95 },
                    { x: 50, y: 63 },
                    { x: 18, y: 95 },
                    { x: 5, y: 82 },
                    { x: 37, y: 50 },
                    { x: 5, y: 18 },
                ],
            },
            {
                id: "check",
                name: "Check",
                points: [
                    { x: 4, y: 52 },
                    { x: 20, y: 36 },
                    { x: 42, y: 58 },
                    { x: 80, y: 18 },
                    { x: 96, y: 34 },
                    { x: 42, y: 90 },
                ],
            },
            {
                id: "star",
                name: "Star",
                points: [
                    { x: 50, y: 2 },
                    { x: 61, y: 36 },
                    { x: 97, y: 36 },
                    { x: 68, y: 57 },
                    { x: 79, y: 94 },
                    { x: 50, y: 72 },
                    { x: 21, y: 94 },
                    { x: 32, y: 57 },
                    { x: 3, y: 36 },
                    { x: 39, y: 36 },
                ],
            },
            {
                id: "bolt",
                name: "Bolt",
                points: [
                    { x: 54, y: 2 },
                    { x: 20, y: 53 },
                    { x: 46, y: 53 },
                    { x: 37, y: 98 },
                    { x: 82, y: 39 },
                    { x: 55, y: 39 },
                ],
            },
            {
                id: "hourglass",
                name: "Hourglass",
                points: [
                    { x: 15, y: 5 },
                    { x: 85, y: 5 },
                    { x: 65, y: 50 },
                    { x: 85, y: 95 },
                    { x: 15, y: 95 },
                    { x: 35, y: 50 },
                ],
            },
        ],
    },
    {
        id: "tools",
        name: "Tools",
        presets: [
            {
                id: "hammer",
                name: "Hammer",
                points: [
                    { x: 6, y: 12 },
                    { x: 54, y: 12 },
                    { x: 54, y: 7 },
                    { x: 94, y: 22 },
                    { x: 94, y: 36 },
                    { x: 54, y: 36 },
                    { x: 54, y: 29 },
                    { x: 46, y: 29 },
                    { x: 27, y: 95 },
                    { x: 12, y: 90 },
                    { x: 34, y: 29 },
                    { x: 6, y: 29 },
                ],
            },
            {
                id: "sickle",
                name: "Sickle",
                points: [
                    { x: 15, y: 91 },
                    { x: 27, y: 96 },
                    { x: 50, y: 50 },
                    { x: 66, y: 46 },
                    { x: 79, y: 36 },
                    { x: 88, y: 24 },
                    { x: 94, y: 10 },
                    { x: 82, y: 20 },
                    { x: 68, y: 27 },
                    { x: 53, y: 29 },
                    { x: 40, y: 26 },
                    { x: 31, y: 19 },
                    { x: 37, y: 34 },
                    { x: 51, y: 43 },
                ],
            },
            {
                id: "axe-tool",
                name: "Axe",
                points: [
                    { x: 12, y: 88 },
                    { x: 23, y: 94 },
                    { x: 53, y: 38 },
                    { x: 65, y: 43 },
                    { x: 91, y: 29 },
                    { x: 94, y: 12 },
                    { x: 73, y: 9 },
                    { x: 52, y: 20 },
                    { x: 48, y: 31 },
                ],
            },
            {
                id: "pickaxe",
                name: "Pickaxe",
                points: [
                    { x: 42, y: 94 },
                    { x: 57, y: 94 },
                    { x: 54, y: 35 },
                    { x: 61, y: 32 },
                    { x: 89, y: 38 },
                    { x: 96, y: 30 },
                    { x: 62, y: 16 },
                    { x: 50, y: 19 },
                    { x: 38, y: 16 },
                    { x: 4, y: 30 },
                    { x: 11, y: 38 },
                    { x: 39, y: 32 },
                    { x: 46, y: 35 },
                ],
            },
            {
                id: "shovel",
                name: "Shovel",
                points: [
                    { x: 43, y: 8 },
                    { x: 57, y: 8 },
                    { x: 57, y: 63 },
                    { x: 69, y: 70 },
                    { x: 72, y: 83 },
                    { x: 62, y: 96 },
                    { x: 38, y: 96 },
                    { x: 28, y: 83 },
                    { x: 31, y: 70 },
                    { x: 43, y: 63 },
                ],
            },
            {
                id: "screwdriver",
                name: "Screwdriver",
                points: [
                    { x: 46, y: 4 },
                    { x: 54, y: 4 },
                    { x: 57, y: 54 },
                    { x: 69, y: 62 },
                    { x: 70, y: 88 },
                    { x: 61, y: 97 },
                    { x: 39, y: 97 },
                    { x: 30, y: 88 },
                    { x: 31, y: 62 },
                    { x: 43, y: 54 },
                ],
            },
            {
                id: "wrench",
                name: "Wrench",
                points: [
                    { x: 20, y: 92 },
                    { x: 8, y: 80 },
                    { x: 40, y: 48 },
                    { x: 34, y: 30 },
                    { x: 41, y: 14 },
                    { x: 57, y: 7 },
                    { x: 52, y: 23 },
                    { x: 61, y: 32 },
                    { x: 77, y: 27 },
                    { x: 70, y: 43 },
                    { x: 54, y: 50 },
                    { x: 46, y: 45 },
                ],
            },
            {
                id: "saw",
                name: "Saw",
                points: [
                    { x: 5, y: 22 },
                    { x: 70, y: 22 },
                    { x: 95, y: 40 },
                    { x: 75, y: 57 },
                    { x: 66, y: 48 },
                    { x: 60, y: 57 },
                    { x: 54, y: 48 },
                    { x: 48, y: 57 },
                    { x: 42, y: 48 },
                    { x: 36, y: 57 },
                    { x: 30, y: 48 },
                    { x: 24, y: 57 },
                    { x: 18, y: 48 },
                    { x: 5, y: 48 },
                ],
            },
            {
                id: "pliers",
                name: "Pliers",
                points: [
                    { x: 31, y: 5 },
                    { x: 46, y: 34 },
                    { x: 50, y: 39 },
                    { x: 54, y: 34 },
                    { x: 69, y: 5 },
                    { x: 72, y: 25 },
                    { x: 60, y: 47 },
                    { x: 82, y: 91 },
                    { x: 68, y: 97 },
                    { x: 50, y: 58 },
                    { x: 32, y: 97 },
                    { x: 18, y: 91 },
                    { x: 40, y: 47 },
                    { x: 28, y: 25 },
                ],
            },
        ],
    },
    {
        id: "weapons",
        name: "Weapons",
        presets: [
            {
                id: "sword",
                name: "Sword",
                points: [
                    { x: 48, y: 2 },
                    { x: 58, y: 10 },
                    { x: 57, y: 65 },
                    { x: 69, y: 65 },
                    { x: 69, y: 74 },
                    { x: 56, y: 74 },
                    { x: 56, y: 90 },
                    { x: 50, y: 98 },
                    { x: 44, y: 90 },
                    { x: 44, y: 74 },
                    { x: 31, y: 74 },
                    { x: 31, y: 65 },
                    { x: 43, y: 65 },
                    { x: 43, y: 10 },
                ],
            },
            {
                id: "dagger",
                name: "Dagger",
                points: [
                    { x: 50, y: 3 },
                    { x: 62, y: 20 },
                    { x: 57, y: 62 },
                    { x: 78, y: 67 },
                    { x: 74, y: 77 },
                    { x: 56, y: 73 },
                    { x: 56, y: 91 },
                    { x: 50, y: 98 },
                    { x: 44, y: 91 },
                    { x: 44, y: 73 },
                    { x: 26, y: 77 },
                    { x: 22, y: 67 },
                    { x: 43, y: 62 },
                    { x: 38, y: 20 },
                ],
            },
            {
                id: "spear",
                name: "Spear",
                points: [
                    { x: 50, y: 2 },
                    { x: 64, y: 24 },
                    { x: 55, y: 29 },
                    { x: 55, y: 94 },
                    { x: 50, y: 99 },
                    { x: 45, y: 94 },
                    { x: 45, y: 29 },
                    { x: 36, y: 24 },
                ],
            },
            {
                id: "battle-axe",
                name: "Battle axe",
                points: [
                    { x: 44, y: 97 },
                    { x: 56, y: 97 },
                    { x: 56, y: 47 },
                    { x: 72, y: 52 },
                    { x: 92, y: 43 },
                    { x: 96, y: 22 },
                    { x: 78, y: 14 },
                    { x: 57, y: 24 },
                    { x: 50, y: 20 },
                    { x: 43, y: 24 },
                    { x: 22, y: 14 },
                    { x: 4, y: 22 },
                    { x: 8, y: 43 },
                    { x: 28, y: 52 },
                    { x: 44, y: 47 },
                ],
            },
            {
                id: "mace",
                name: "Mace",
                points: [
                    { x: 45, y: 98 },
                    { x: 55, y: 98 },
                    { x: 55, y: 49 },
                    { x: 63, y: 44 },
                    { x: 75, y: 47 },
                    { x: 83, y: 37 },
                    { x: 79, y: 25 },
                    { x: 88, y: 15 },
                    { x: 74, y: 12 },
                    { x: 67, y: 3 },
                    { x: 58, y: 13 },
                    { x: 50, y: 7 },
                    { x: 42, y: 13 },
                    { x: 33, y: 3 },
                    { x: 26, y: 12 },
                    { x: 12, y: 15 },
                    { x: 21, y: 25 },
                    { x: 17, y: 37 },
                    { x: 25, y: 47 },
                    { x: 37, y: 44 },
                    { x: 45, y: 49 },
                ],
            },
            {
                id: "bow",
                name: "Bow",
                points: [
                    { x: 21, y: 5 },
                    { x: 36, y: 18 },
                    { x: 48, y: 37 },
                    { x: 51, y: 50 },
                    { x: 48, y: 63 },
                    { x: 36, y: 82 },
                    { x: 21, y: 95 },
                    { x: 34, y: 72 },
                    { x: 42, y: 53 },
                    { x: 10, y: 53 },
                    { x: 10, y: 47 },
                    { x: 42, y: 47 },
                    { x: 34, y: 28 },
                ],
            },
            {
                id: "arrow-weapon",
                name: "Arrow",
                points: [
                    { x: 5, y: 47 },
                    { x: 70, y: 47 },
                    { x: 70, y: 32 },
                    { x: 97, y: 50 },
                    { x: 70, y: 68 },
                    { x: 70, y: 53 },
                    { x: 5, y: 53 },
                    { x: 17, y: 65 },
                    { x: 10, y: 70 },
                    { x: 0, y: 50 },
                    { x: 10, y: 30 },
                    { x: 17, y: 35 },
                ],
            },
            {
                id: "war-shield",
                name: "War shield",
                points: [
                    { x: 50, y: 2 },
                    { x: 91, y: 15 },
                    { x: 88, y: 58 },
                    { x: 76, y: 80 },
                    { x: 50, y: 98 },
                    { x: 24, y: 80 },
                    { x: 12, y: 58 },
                    { x: 9, y: 15 },
                ],
            },
        ],
    },
    {
        id: "nature",
        name: "Nature",
        presets: [
            {
                id: "leaf",
                name: "Leaf",
                points: [
                    { x: 8, y: 88 },
                    { x: 14, y: 62 },
                    { x: 27, y: 38 },
                    { x: 48, y: 20 },
                    { x: 91, y: 7 },
                    { x: 82, y: 48 },
                    { x: 66, y: 70 },
                    { x: 44, y: 85 },
                    { x: 19, y: 93 },
                    { x: 44, y: 62 },
                    { x: 65, y: 43 },
                ],
            },
            {
                id: "flame",
                name: "Flame",
                points: [
                    { x: 50, y: 2 },
                    { x: 63, y: 27 },
                    { x: 62, y: 44 },
                    { x: 78, y: 31 },
                    { x: 91, y: 56 },
                    { x: 89, y: 75 },
                    { x: 76, y: 91 },
                    { x: 50, y: 98 },
                    { x: 24, y: 91 },
                    { x: 11, y: 75 },
                    { x: 9, y: 57 },
                    { x: 20, y: 35 },
                    { x: 29, y: 52 },
                    { x: 32, y: 32 },
                ],
            },
            {
                id: "water-drop",
                name: "Drop",
                points: [
                    { x: 50, y: 2 },
                    { x: 68, y: 29 },
                    { x: 84, y: 55 },
                    { x: 88, y: 70 },
                    { x: 82, y: 86 },
                    { x: 68, y: 96 },
                    { x: 50, y: 99 },
                    { x: 32, y: 96 },
                    { x: 18, y: 86 },
                    { x: 12, y: 70 },
                    { x: 16, y: 55 },
                    { x: 32, y: 29 },
                ],
            },
            {
                id: "mountain",
                name: "Mountain",
                points: [
                    { x: 2, y: 91 },
                    { x: 28, y: 49 },
                    { x: 40, y: 64 },
                    { x: 60, y: 26 },
                    { x: 98, y: 91 },
                    { x: 72, y: 91 },
                    { x: 59, y: 68 },
                    { x: 48, y: 82 },
                    { x: 29, y: 64 },
                    { x: 15, y: 91 },
                ],
            },
            {
                id: "pine-tree",
                name: "Pine tree",
                points: [
                    { x: 50, y: 2 },
                    { x: 74, y: 32 },
                    { x: 61, y: 32 },
                    { x: 84, y: 59 },
                    { x: 65, y: 59 },
                    { x: 92, y: 86 },
                    { x: 58, y: 86 },
                    { x: 58, y: 98 },
                    { x: 42, y: 98 },
                    { x: 42, y: 86 },
                    { x: 8, y: 86 },
                    { x: 35, y: 59 },
                    { x: 16, y: 59 },
                    { x: 39, y: 32 },
                    { x: 26, y: 32 },
                ],
            },
            {
                id: "sun",
                name: "Sun",
                points: [
                    { x: 50, y: 0 },
                    { x: 59, y: 22 },
                    { x: 78, y: 8 },
                    { x: 76, y: 32 },
                    { x: 100, y: 31 },
                    { x: 80, y: 50 },
                    { x: 100, y: 69 },
                    { x: 76, y: 68 },
                    { x: 78, y: 92 },
                    { x: 59, y: 78 },
                    { x: 50, y: 100 },
                    { x: 41, y: 78 },
                    { x: 22, y: 92 },
                    { x: 24, y: 68 },
                    { x: 0, y: 69 },
                    { x: 20, y: 50 },
                    { x: 0, y: 31 },
                    { x: 24, y: 32 },
                    { x: 22, y: 8 },
                    { x: 41, y: 22 },
                ],
            },
            {
                id: "flower",
                name: "Flower",
                points: [
                    { x: 50, y: 22 },
                    { x: 61, y: 4 },
                    { x: 71, y: 25 },
                    { x: 94, y: 21 },
                    { x: 80, y: 43 },
                    { x: 98, y: 57 },
                    { x: 72, y: 62 },
                    { x: 72, y: 89 },
                    { x: 50, y: 73 },
                    { x: 28, y: 89 },
                    { x: 28, y: 62 },
                    { x: 2, y: 57 },
                    { x: 20, y: 43 },
                    { x: 6, y: 21 },
                    { x: 29, y: 25 },
                    { x: 39, y: 4 },
                ],
            },
        ],
    },
    {
        id: "animals",
        name: "Animals",
        presets: [
            {
                id: "cat-head",
                name: "Cat",
                points: [
                    { x: 14, y: 18 },
                    { x: 35, y: 28 },
                    { x: 50, y: 24 },
                    { x: 65, y: 28 },
                    { x: 86, y: 18 },
                    { x: 82, y: 57 },
                    { x: 72, y: 80 },
                    { x: 50, y: 94 },
                    { x: 28, y: 80 },
                    { x: 18, y: 57 },
                ],
            },
            {
                id: "fish",
                name: "Fish",
                points: [
                    { x: 4, y: 50 },
                    { x: 23, y: 30 },
                    { x: 23, y: 15 },
                    { x: 42, y: 28 },
                    { x: 70, y: 25 },
                    { x: 95, y: 50 },
                    { x: 70, y: 75 },
                    { x: 42, y: 72 },
                    { x: 23, y: 85 },
                    { x: 23, y: 70 },
                ],
            },
            {
                id: "bird",
                name: "Bird",
                points: [
                    { x: 4, y: 52 },
                    { x: 28, y: 33 },
                    { x: 46, y: 42 },
                    { x: 59, y: 23 },
                    { x: 72, y: 42 },
                    { x: 96, y: 32 },
                    { x: 78, y: 56 },
                    { x: 65, y: 62 },
                    { x: 50, y: 83 },
                    { x: 38, y: 62 },
                    { x: 20, y: 62 },
                ],
            },
            {
                id: "butterfly",
                name: "Butterfly",
                points: [
                    { x: 48, y: 43 },
                    { x: 28, y: 11 },
                    { x: 6, y: 21 },
                    { x: 14, y: 48 },
                    { x: 5, y: 76 },
                    { x: 31, y: 89 },
                    { x: 48, y: 59 },
                    { x: 52, y: 59 },
                    { x: 69, y: 89 },
                    { x: 95, y: 76 },
                    { x: 86, y: 48 },
                    { x: 94, y: 21 },
                    { x: 72, y: 11 },
                    { x: 52, y: 43 },
                ],
            },
            {
                id: "rabbit-head",
                name: "Rabbit",
                points: [
                    { x: 29, y: 4 },
                    { x: 42, y: 7 },
                    { x: 46, y: 39 },
                    { x: 54, y: 39 },
                    { x: 58, y: 7 },
                    { x: 71, y: 4 },
                    { x: 68, y: 43 },
                    { x: 83, y: 60 },
                    { x: 78, y: 82 },
                    { x: 50, y: 97 },
                    { x: 22, y: 82 },
                    { x: 17, y: 60 },
                    { x: 32, y: 43 },
                ],
            },
        ],
    },
    {
        id: "technology",
        name: "Technology",
        presets: [
            {
                id: "monitor",
                name: "Monitor",
                points: [
                    { x: 5, y: 10 },
                    { x: 95, y: 10 },
                    { x: 95, y: 70 },
                    { x: 58, y: 70 },
                    { x: 58, y: 82 },
                    { x: 75, y: 82 },
                    { x: 75, y: 92 },
                    { x: 25, y: 92 },
                    { x: 25, y: 82 },
                    { x: 42, y: 82 },
                    { x: 42, y: 70 },
                    { x: 5, y: 70 },
                ],
            },
            {
                id: "phone",
                name: "Phone",
                points: [
                    { x: 28, y: 3 },
                    { x: 72, y: 3 },
                    { x: 78, y: 10 },
                    { x: 78, y: 90 },
                    { x: 72, y: 97 },
                    { x: 28, y: 97 },
                    { x: 22, y: 90 },
                    { x: 22, y: 10 },
                ],
            },
            {
                id: "battery",
                name: "Battery",
                points: [
                    { x: 5, y: 25 },
                    { x: 85, y: 25 },
                    { x: 85, y: 38 },
                    { x: 96, y: 38 },
                    { x: 96, y: 62 },
                    { x: 85, y: 62 },
                    { x: 85, y: 75 },
                    { x: 5, y: 75 },
                ],
            },
            {
                id: "chip",
                name: "Chip",
                points: [
                    { x: 20, y: 20 },
                    { x: 35, y: 20 },
                    { x: 35, y: 4 },
                    { x: 45, y: 4 },
                    { x: 45, y: 20 },
                    { x: 55, y: 20 },
                    { x: 55, y: 4 },
                    { x: 65, y: 4 },
                    { x: 65, y: 20 },
                    { x: 80, y: 20 },
                    { x: 80, y: 35 },
                    { x: 96, y: 35 },
                    { x: 96, y: 45 },
                    { x: 80, y: 45 },
                    { x: 80, y: 55 },
                    { x: 96, y: 55 },
                    { x: 96, y: 65 },
                    { x: 80, y: 65 },
                    { x: 80, y: 80 },
                    { x: 65, y: 80 },
                    { x: 65, y: 96 },
                    { x: 55, y: 96 },
                    { x: 55, y: 80 },
                    { x: 45, y: 80 },
                    { x: 45, y: 96 },
                    { x: 35, y: 96 },
                    { x: 35, y: 80 },
                    { x: 20, y: 80 },
                    { x: 20, y: 65 },
                    { x: 4, y: 65 },
                    { x: 4, y: 55 },
                    { x: 20, y: 55 },
                    { x: 20, y: 45 },
                    { x: 4, y: 45 },
                    { x: 4, y: 35 },
                    { x: 20, y: 35 },
                ],
            },
            {
                id: "cursor",
                name: "Cursor",
                points: [
                    { x: 12, y: 5 },
                    { x: 88, y: 56 },
                    { x: 57, y: 61 },
                    { x: 72, y: 88 },
                    { x: 59, y: 95 },
                    { x: 44, y: 67 },
                    { x: 23, y: 91 },
                ],
            },
            {
                id: "wifi",
                name: "WiFi",
                points: [
                    { x: 5, y: 34 },
                    { x: 20, y: 18 },
                    { x: 50, y: 10 },
                    { x: 80, y: 18 },
                    { x: 95, y: 34 },
                    { x: 84, y: 45 },
                    { x: 69, y: 33 },
                    { x: 50, y: 29 },
                    { x: 31, y: 33 },
                    { x: 16, y: 45 },
                    { x: 27, y: 56 },
                    { x: 38, y: 48 },
                    { x: 50, y: 46 },
                    { x: 62, y: 48 },
                    { x: 73, y: 56 },
                    { x: 62, y: 67 },
                    { x: 50, y: 62 },
                    { x: 38, y: 67 },
                    { x: 50, y: 88 },
                ],
            },
        ],
    },
    {
        id: "transport",
        name: "Transport",
        presets: [
            {
                id: "plane",
                name: "Plane",
                points: [
                    { x: 4, y: 45 },
                    { x: 39, y: 38 },
                    { x: 51, y: 5 },
                    { x: 61, y: 5 },
                    { x: 58, y: 38 },
                    { x: 96, y: 45 },
                    { x: 96, y: 55 },
                    { x: 58, y: 62 },
                    { x: 62, y: 87 },
                    { x: 54, y: 87 },
                    { x: 49, y: 66 },
                    { x: 39, y: 95 },
                    { x: 31, y: 95 },
                    { x: 39, y: 63 },
                    { x: 4, y: 55 },
                ],
            },
            {
                id: "rocket",
                name: "Rocket",
                points: [
                    { x: 50, y: 2 },
                    { x: 65, y: 18 },
                    { x: 70, y: 44 },
                    { x: 84, y: 61 },
                    { x: 70, y: 62 },
                    { x: 66, y: 84 },
                    { x: 57, y: 76 },
                    { x: 50, y: 98 },
                    { x: 43, y: 76 },
                    { x: 34, y: 84 },
                    { x: 30, y: 62 },
                    { x: 16, y: 61 },
                    { x: 30, y: 44 },
                    { x: 35, y: 18 },
                ],
            },
            {
                id: "boat",
                name: "Boat",
                points: [
                    { x: 10, y: 54 },
                    { x: 90, y: 54 },
                    { x: 80, y: 80 },
                    { x: 67, y: 90 },
                    { x: 33, y: 90 },
                    { x: 20, y: 80 },
                    { x: 5, y: 60 },
                    { x: 38, y: 60 },
                    { x: 38, y: 15 },
                    { x: 43, y: 15 },
                    { x: 43, y: 52 },
                    { x: 75, y: 52 },
                    { x: 43, y: 20 },
                ],
            },
            {
                id: "car",
                name: "Car",
                points: [
                    { x: 5, y: 52 },
                    { x: 17, y: 37 },
                    { x: 30, y: 32 },
                    { x: 40, y: 17 },
                    { x: 70, y: 17 },
                    { x: 83, y: 38 },
                    { x: 95, y: 45 },
                    { x: 98, y: 70 },
                    { x: 85, y: 70 },
                    { x: 78, y: 84 },
                    { x: 64, y: 84 },
                    { x: 57, y: 70 },
                    { x: 35, y: 70 },
                    { x: 28, y: 84 },
                    { x: 14, y: 84 },
                    { x: 7, y: 70 },
                ],
            },
        ],
    },
    {
        id: "food",
        name: "Food & drinks",
        presets: [
            {
                id: "cup",
                name: "Cup",
                points: [
                    { x: 17, y: 20 },
                    { x: 68, y: 20 },
                    { x: 68, y: 30 },
                    { x: 85, y: 30 },
                    { x: 94, y: 42 },
                    { x: 94, y: 57 },
                    { x: 85, y: 70 },
                    { x: 67, y: 70 },
                    { x: 61, y: 86 },
                    { x: 25, y: 86 },
                    { x: 17, y: 60 },
                ],
            },
            {
                id: "bottle",
                name: "Bottle",
                points: [
                    { x: 39, y: 4 },
                    { x: 61, y: 4 },
                    { x: 61, y: 22 },
                    { x: 69, y: 32 },
                    { x: 72, y: 91 },
                    { x: 65, y: 98 },
                    { x: 35, y: 98 },
                    { x: 28, y: 91 },
                    { x: 31, y: 32 },
                    { x: 39, y: 22 },
                ],
            },
            {
                id: "apple",
                name: "Apple",
                points: [
                    { x: 52, y: 20 },
                    { x: 63, y: 5 },
                    { x: 76, y: 9 },
                    { x: 65, y: 23 },
                    { x: 82, y: 27 },
                    { x: 94, y: 43 },
                    { x: 91, y: 71 },
                    { x: 75, y: 91 },
                    { x: 58, y: 96 },
                    { x: 50, y: 91 },
                    { x: 42, y: 96 },
                    { x: 25, y: 91 },
                    { x: 9, y: 71 },
                    { x: 6, y: 43 },
                    { x: 18, y: 27 },
                    { x: 37, y: 23 },
                ],
            },
            {
                id: "pizza",
                name: "Pizza",
                points: [
                    { x: 50, y: 4 },
                    { x: 96, y: 86 },
                    { x: 82, y: 96 },
                    { x: 18, y: 96 },
                    { x: 4, y: 86 },
                ],
            },
            {
                id: "ice-cream",
                name: "Ice cream",
                points: [
                    { x: 27, y: 34 },
                    { x: 25, y: 20 },
                    { x: 34, y: 8 },
                    { x: 50, y: 4 },
                    { x: 66, y: 8 },
                    { x: 75, y: 20 },
                    { x: 73, y: 34 },
                    { x: 63, y: 44 },
                    { x: 58, y: 44 },
                    { x: 50, y: 97 },
                    { x: 42, y: 44 },
                    { x: 37, y: 44 },
                ],
            },
        ],
    },
    {
        id: "buildings",
        name: "Buildings",
        presets: [
            {
                id: "simple-house",
                name: "House",
                points: [
                    { x: 5, y: 45 },
                    { x: 50, y: 5 },
                    { x: 95, y: 45 },
                    { x: 84, y: 45 },
                    { x: 84, y: 95 },
                    { x: 62, y: 95 },
                    { x: 62, y: 66 },
                    { x: 38, y: 66 },
                    { x: 38, y: 95 },
                    { x: 16, y: 95 },
                    { x: 16, y: 45 },
                ],
            },
            {
                id: "castle",
                name: "Castle",
                points: [
                    { x: 8, y: 15 },
                    { x: 22, y: 15 },
                    { x: 22, y: 30 },
                    { x: 38, y: 30 },
                    { x: 38, y: 12 },
                    { x: 48, y: 12 },
                    { x: 48, y: 30 },
                    { x: 52, y: 30 },
                    { x: 52, y: 12 },
                    { x: 62, y: 12 },
                    { x: 62, y: 30 },
                    { x: 78, y: 30 },
                    { x: 78, y: 15 },
                    { x: 92, y: 15 },
                    { x: 92, y: 95 },
                    { x: 62, y: 95 },
                    { x: 62, y: 66 },
                    { x: 38, y: 66 },
                    { x: 38, y: 95 },
                    { x: 8, y: 95 },
                ],
            },
            {
                id: "tower",
                name: "Tower",
                points: [
                    { x: 26, y: 10 },
                    { x: 38, y: 10 },
                    { x: 38, y: 25 },
                    { x: 44, y: 25 },
                    { x: 44, y: 10 },
                    { x: 56, y: 10 },
                    { x: 56, y: 25 },
                    { x: 62, y: 25 },
                    { x: 62, y: 10 },
                    { x: 74, y: 10 },
                    { x: 69, y: 95 },
                    { x: 31, y: 95 },
                ],
            },
            {
                id: "factory",
                name: "Factory",
                points: [
                    { x: 5, y: 40 },
                    { x: 26, y: 25 },
                    { x: 26, y: 40 },
                    { x: 48, y: 25 },
                    { x: 48, y: 40 },
                    { x: 70, y: 25 },
                    { x: 70, y: 15 },
                    { x: 82, y: 15 },
                    { x: 82, y: 40 },
                    { x: 95, y: 40 },
                    { x: 95, y: 95 },
                    { x: 5, y: 95 },
                ],
            },
        ],
    },
    {
        id: "signs",
        name: "Signs & navigation",
        presets: [
            {
                id: "warning",
                name: "Warning",
                points: [
                    { x: 50, y: 3 },
                    { x: 98, y: 94 },
                    { x: 2, y: 94 },
                ],
            },
            {
                id: "location",
                name: "Location pin",
                points: [
                    { x: 50, y: 2 },
                    { x: 69, y: 8 },
                    { x: 83, y: 22 },
                    { x: 90, y: 40 },
                    { x: 87, y: 58 },
                    { x: 74, y: 76 },
                    { x: 50, y: 98 },
                    { x: 26, y: 76 },
                    { x: 13, y: 58 },
                    { x: 10, y: 40 },
                    { x: 17, y: 22 },
                    { x: 31, y: 8 },
                ],
            },
            {
                id: "key",
                name: "Key",
                points: [
                    { x: 8, y: 35 },
                    { x: 17, y: 18 },
                    { x: 35, y: 10 },
                    { x: 52, y: 17 },
                    { x: 61, y: 30 },
                    { x: 96, y: 30 },
                    { x: 96, y: 43 },
                    { x: 87, y: 43 },
                    { x: 87, y: 54 },
                    { x: 75, y: 54 },
                    { x: 75, y: 43 },
                    { x: 61, y: 43 },
                    { x: 52, y: 57 },
                    { x: 35, y: 64 },
                    { x: 17, y: 56 },
                ],
            },
            {
                id: "lock",
                name: "Lock",
                points: [
                    { x: 26, y: 38 },
                    { x: 26, y: 23 },
                    { x: 34, y: 9 },
                    { x: 50, y: 4 },
                    { x: 66, y: 9 },
                    { x: 74, y: 23 },
                    { x: 74, y: 38 },
                    { x: 88, y: 38 },
                    { x: 88, y: 94 },
                    { x: 12, y: 94 },
                    { x: 12, y: 38 },
                    { x: 38, y: 38 },
                    { x: 38, y: 25 },
                    { x: 43, y: 19 },
                    { x: 57, y: 19 },
                    { x: 62, y: 25 },
                    { x: 62, y: 38 },
                ],
            },
            {
                id: "flag",
                name: "Flag",
                points: [
                    { x: 15, y: 4 },
                    { x: 23, y: 4 },
                    { x: 23, y: 13 },
                    { x: 86, y: 13 },
                    { x: 69, y: 35 },
                    { x: 86, y: 57 },
                    { x: 23, y: 57 },
                    { x: 23, y: 96 },
                    { x: 15, y: 96 },
                ],
            },
        ],
    },
    {
        id: "gaming",
        name: "Gaming & fantasy",
        presets: [
            {
                id: "crown",
                name: "Crown",
                points: [
                    { x: 5, y: 25 },
                    { x: 28, y: 45 },
                    { x: 37, y: 14 },
                    { x: 50, y: 43 },
                    { x: 63, y: 14 },
                    { x: 72, y: 45 },
                    { x: 95, y: 25 },
                    { x: 84, y: 82 },
                    { x: 16, y: 82 },
                ],
            },
            {
                id: "gem",
                name: "Gem",
                points: [
                    { x: 20, y: 15 },
                    { x: 80, y: 15 },
                    { x: 98, y: 38 },
                    { x: 50, y: 96 },
                    { x: 2, y: 38 },
                ],
            },
            {
                id: "trophy",
                name: "Trophy",
                points: [
                    { x: 22, y: 10 },
                    { x: 78, y: 10 },
                    { x: 78, y: 20 },
                    { x: 94, y: 20 },
                    { x: 90, y: 48 },
                    { x: 73, y: 58 },
                    { x: 60, y: 70 },
                    { x: 58, y: 83 },
                    { x: 76, y: 83 },
                    { x: 76, y: 94 },
                    { x: 24, y: 94 },
                    { x: 24, y: 83 },
                    { x: 42, y: 83 },
                    { x: 40, y: 70 },
                    { x: 27, y: 58 },
                    { x: 10, y: 48 },
                    { x: 6, y: 20 },
                    { x: 22, y: 20 },
                ],
            },
            {
                id: "potion",
                name: "Potion",
                points: [
                    { x: 38, y: 4 },
                    { x: 62, y: 4 },
                    { x: 62, y: 18 },
                    { x: 68, y: 23 },
                    { x: 68, y: 35 },
                    { x: 84, y: 55 },
                    { x: 86, y: 80 },
                    { x: 72, y: 95 },
                    { x: 28, y: 95 },
                    { x: 14, y: 80 },
                    { x: 16, y: 55 },
                    { x: 32, y: 35 },
                    { x: 32, y: 23 },
                    { x: 38, y: 18 },
                ],
            },
            {
                id: "crystal",
                name: "Crystal",
                points: [
                    { x: 50, y: 2 },
                    { x: 74, y: 30 },
                    { x: 64, y: 92 },
                    { x: 50, y: 99 },
                    { x: 36, y: 92 },
                    { x: 26, y: 30 },
                ],
            },
        ],
    },
    {
        id: "space",
        name: "Space",
        presets: [
            {
                id: "space-rocket",
                name: "Rocket",
                points: [
                    { x: 50, y: 2 },
                    { x: 67, y: 22 },
                    { x: 70, y: 49 },
                    { x: 85, y: 65 },
                    { x: 68, y: 65 },
                    { x: 63, y: 87 },
                    { x: 54, y: 77 },
                    { x: 50, y: 99 },
                    { x: 46, y: 77 },
                    { x: 37, y: 87 },
                    { x: 32, y: 65 },
                    { x: 15, y: 65 },
                    { x: 30, y: 49 },
                    { x: 33, y: 22 },
                ],
            },
            {
                id: "planet",
                name: "Planet",
                points: [
                    { x: 13, y: 50 },
                    { x: 20, y: 31 },
                    { x: 35, y: 18 },
                    { x: 55, y: 15 },
                    { x: 72, y: 23 },
                    { x: 81, y: 35 },
                    { x: 98, y: 29 },
                    { x: 91, y: 46 },
                    { x: 82, y: 57 },
                    { x: 75, y: 75 },
                    { x: 57, y: 86 },
                    { x: 36, y: 84 },
                    { x: 21, y: 72 },
                    { x: 14, y: 60 },
                    { x: 2, y: 71 },
                    { x: 8, y: 56 },
                ],
            },
            {
                id: "satellite",
                name: "Satellite",
                points: [
                    { x: 37, y: 37 },
                    { x: 63, y: 37 },
                    { x: 63, y: 63 },
                    { x: 37, y: 63 },
                    { x: 37, y: 58 },
                    { x: 10, y: 78 },
                    { x: 4, y: 68 },
                    { x: 34, y: 50 },
                    { x: 4, y: 32 },
                    { x: 10, y: 22 },
                    { x: 37, y: 42 },
                    { x: 63, y: 42 },
                    { x: 90, y: 22 },
                    { x: 96, y: 32 },
                    { x: 66, y: 50 },
                    { x: 96, y: 68 },
                    { x: 90, y: 78 },
                    { x: 63, y: 58 },
                ],
            },
            {
                id: "moon",
                name: "Moon",
                points: [
                    { x: 76, y: 6 },
                    { x: 57, y: 15 },
                    { x: 43, y: 31 },
                    { x: 38, y: 51 },
                    { x: 44, y: 71 },
                    { x: 59, y: 86 },
                    { x: 79, y: 93 },
                    { x: 59, y: 98 },
                    { x: 37, y: 92 },
                    { x: 20, y: 76 },
                    { x: 11, y: 55 },
                    { x: 14, y: 33 },
                    { x: 27, y: 15 },
                    { x: 48, y: 5 },
                ],
            },
        ],
    },
    {
        id: "weather",
        name: "Weather",
        presets: [
            {
                id: "cloud",
                name: "Cloud",
                points: [
                    { x: 13, y: 72 },
                    { x: 5, y: 60 },
                    { x: 7, y: 45 },
                    { x: 18, y: 35 },
                    { x: 32, y: 35 },
                    { x: 39, y: 18 },
                    { x: 55, y: 11 },
                    { x: 72, y: 17 },
                    { x: 80, y: 32 },
                    { x: 92, y: 38 },
                    { x: 98, y: 51 },
                    { x: 94, y: 66 },
                    { x: 82, y: 75 },
                    { x: 20, y: 75 },
                ],
            },
            {
                id: "lightning",
                name: "Lightning",
                points: [
                    { x: 54, y: 2 },
                    { x: 18, y: 53 },
                    { x: 45, y: 53 },
                    { x: 34, y: 98 },
                    { x: 84, y: 39 },
                    { x: 56, y: 39 },
                ],
            },
            {
                id: "snowflake",
                name: "Snowflake",
                points: [
                    { x: 46, y: 2 },
                    { x: 54, y: 2 },
                    { x: 54, y: 32 },
                    { x: 76, y: 16 },
                    { x: 81, y: 22 },
                    { x: 59, y: 39 },
                    { x: 94, y: 39 },
                    { x: 94, y: 47 },
                    { x: 61, y: 47 },
                    { x: 84, y: 66 },
                    { x: 79, y: 72 },
                    { x: 54, y: 54 },
                    { x: 54, y: 98 },
                    { x: 46, y: 98 },
                    { x: 46, y: 54 },
                    { x: 21, y: 72 },
                    { x: 16, y: 66 },
                    { x: 39, y: 47 },
                    { x: 6, y: 47 },
                    { x: 6, y: 39 },
                    { x: 41, y: 39 },
                    { x: 19, y: 22 },
                    { x: 24, y: 16 },
                    { x: 46, y: 32 },
                ],
            },
            {
                id: "umbrella",
                name: "Umbrella",
                points: [
                    { x: 5, y: 48 },
                    { x: 13, y: 27 },
                    { x: 28, y: 14 },
                    { x: 46, y: 9 },
                    { x: 46, y: 4 },
                    { x: 54, y: 4 },
                    { x: 54, y: 9 },
                    { x: 72, y: 14 },
                    { x: 87, y: 27 },
                    { x: 95, y: 48 },
                    { x: 72, y: 42 },
                    { x: 54, y: 48 },
                    { x: 54, y: 83 },
                    { x: 60, y: 90 },
                    { x: 68, y: 90 },
                    { x: 68, y: 98 },
                    { x: 57, y: 98 },
                    { x: 46, y: 87 },
                    { x: 46, y: 48 },
                    { x: 28, y: 42 },
                ],
            },
        ],
    },
    {
        id: "decorative",
        name: "Decorative",
        presets: [
            {
                id: "burst",
                name: "Burst",
                points: [
                    { x: 50, y: 2 },
                    { x: 61, y: 20 },
                    { x: 81, y: 10 },
                    { x: 80, y: 32 },
                    { x: 98, y: 40 },
                    { x: 83, y: 55 },
                    { x: 94, y: 75 },
                    { x: 71, y: 76 },
                    { x: 62, y: 97 },
                    { x: 48, y: 80 },
                    { x: 28, y: 94 },
                    { x: 27, y: 71 },
                    { x: 5, y: 64 },
                    { x: 21, y: 47 },
                    { x: 5, y: 31 },
                    { x: 29, y: 29 },
                ],
            },
            {
                id: "ticket",
                name: "Ticket",
                points: [
                    { x: 0, y: 10 },
                    { x: 10, y: 10 },
                    { x: 14, y: 20 },
                    { x: 10, y: 30 },
                    { x: 0, y: 30 },
                    { x: 0, y: 70 },
                    { x: 10, y: 70 },
                    { x: 14, y: 80 },
                    { x: 10, y: 90 },
                    { x: 0, y: 90 },
                    { x: 0, y: 100 },
                    { x: 100, y: 100 },
                    { x: 100, y: 90 },
                    { x: 90, y: 90 },
                    { x: 86, y: 80 },
                    { x: 90, y: 70 },
                    { x: 100, y: 70 },
                    { x: 100, y: 30 },
                    { x: 90, y: 30 },
                    { x: 86, y: 20 },
                    { x: 90, y: 10 },
                    { x: 100, y: 10 },
                    { x: 100, y: 0 },
                    { x: 0, y: 0 },
                ],
            },
            {
                id: "ribbon-left",
                name: "Ribbon left",
                points: [
                    { x: 0, y: 15 },
                    { x: 100, y: 15 },
                    { x: 100, y: 85 },
                    { x: 0, y: 85 },
                    { x: 20, y: 50 },
                ],
            },
            {
                id: "ribbon-right",
                name: "Ribbon right",
                points: [
                    { x: 0, y: 15 },
                    { x: 100, y: 15 },
                    { x: 80, y: 50 },
                    { x: 100, y: 85 },
                    { x: 0, y: 85 },
                ],
            },
            {
                id: "frame-cut",
                name: "Cut corners",
                points: [
                    { x: 12, y: 0 },
                    { x: 88, y: 0 },
                    { x: 100, y: 12 },
                    { x: 100, y: 88 },
                    { x: 88, y: 100 },
                    { x: 12, y: 100 },
                    { x: 0, y: 88 },
                    { x: 0, y: 12 },
                ],
            },
            {
                id: "slant",
                name: "Slant",
                points: [
                    { x: 0, y: 15 },
                    { x: 100, y: 0 },
                    { x: 100, y: 85 },
                    { x: 0, y: 100 },
                ],
            },
            {
                id: "wave-block",
                name: "Wave",
                points: [
                    { x: 0, y: 10 },
                    { x: 20, y: 4 },
                    { x: 40, y: 12 },
                    { x: 60, y: 4 },
                    { x: 80, y: 12 },
                    { x: 100, y: 6 },
                    { x: 100, y: 90 },
                    { x: 80, y: 96 },
                    { x: 60, y: 88 },
                    { x: 40, y: 96 },
                    { x: 20, y: 88 },
                    { x: 0, y: 94 },
                ],
            },
        ],
    },
];

export const clipPathPresets = clipPathPresetCategories.flatMap(
    (category) => category.presets,
);
