import {
    createDefaultAnimatedTextConfig,
    type AnimatedTextAnimation,
    type AnimatedTextConfig,
} from "./animated-text.type";

export type AnimatedTextPresetCategory =
    | "neon"
    | "retro"
    | "cyber"
    | "elegant"
    | "mono"
    | "colorful"
    | "soft"
    | "dark";

export interface AnimatedTextPreset {
    id: string;

    title: string;

    category: AnimatedTextPresetCategory;

    config: Omit<AnimatedTextConfig, "text">;
}

type PresetSeed = [
    id: string,
    title: string,
    category: AnimatedTextPresetCategory,
    animation: AnimatedTextAnimation,
    font: string,
    speed: number,
    background: string,
    stroke: string,
    fill: string,
];

const defaults = createDefaultAnimatedTextConfig();

const seeds: PresetSeed[] = [
    [
        "neon-blue",
        "Neon Blue",
        "neon",
        "neon-flicker",
        "Outfit, sans-serif",
        2.8,
        "#050816",
        "#38bdf8",
        "#e0f2fe",
    ],
    [
        "neon-pink",
        "Neon Pink",
        "neon",
        "glow",
        "Outfit, sans-serif",
        3,
        "#120512",
        "#f472b6",
        "#fce7f3",
    ],
    [
        "neon-purple",
        "Neon Purple",
        "neon",
        "pulse",
        "Manrope, sans-serif",
        2.5,
        "#090514",
        "#c084fc",
        "#f3e8ff",
    ],
    [
        "neon-green",
        "Neon Green",
        "neon",
        "neon-flicker",
        '"JetBrains Mono", monospace',
        2,
        "#030a06",
        "#4ade80",
        "#dcfce7",
    ],
    [
        "electric-cyan",
        "Electric Cyan",
        "neon",
        "dash",
        "Inter, sans-serif",
        2.2,
        "#020617",
        "#22d3ee",
        "#cffafe",
    ],
    [
        "laser-red",
        "Laser Red",
        "neon",
        "flicker",
        "Impact, sans-serif",
        1.6,
        "#0c0202",
        "#ef4444",
        "#fee2e2",
    ],

    [
        "arcade",
        "Arcade",
        "retro",
        "flicker",
        '"Courier New", monospace',
        1.8,
        "#151515",
        "#facc15",
        "#fef08a",
    ],
    [
        "retro-wave",
        "Retro Wave",
        "retro",
        "wave",
        "Impact, sans-serif",
        2.8,
        "#170b2d",
        "#ec4899",
        "#22d3ee",
    ],
    [
        "synthwave",
        "Synthwave",
        "retro",
        "glow",
        "Outfit, sans-serif",
        3,
        "#14052b",
        "#f472b6",
        "#67e8f9",
    ],
    [
        "old-terminal",
        "Old Terminal",
        "retro",
        "flicker",
        '"JetBrains Mono", monospace',
        1.5,
        "#071207",
        "#22c55e",
        "#86efac",
    ],
    [
        "amber-terminal",
        "Amber Terminal",
        "retro",
        "tracking",
        '"JetBrains Mono", monospace',
        2.8,
        "#120d03",
        "#f59e0b",
        "#fde68a",
    ],
    [
        "vhs",
        "VHS",
        "retro",
        "glitch",
        '"Trebuchet MS", sans-serif',
        1.2,
        "#101020",
        "#fb7185",
        "#5eead4",
    ],

    [
        "matrix",
        "Matrix",
        "cyber",
        "dash",
        '"JetBrains Mono", monospace',
        1.8,
        "#020805",
        "#00ff66",
        "#bbf7d0",
    ],
    [
        "cyber-blue",
        "Cyber Blue",
        "cyber",
        "glitch",
        '"JetBrains Mono", monospace',
        1.4,
        "#020617",
        "#2563eb",
        "#93c5fd",
    ],
    [
        "cyber-red",
        "Cyber Red",
        "cyber",
        "glitch",
        '"JetBrains Mono", monospace',
        1.1,
        "#090303",
        "#f43f5e",
        "#fecdd3",
    ],
    [
        "hacker",
        "Hacker",
        "cyber",
        "flicker",
        '"Courier New", monospace',
        1.3,
        "#000000",
        "#16a34a",
        "#4ade80",
    ],
    [
        "ai-core",
        "AI Core",
        "cyber",
        "pulse",
        "Inter, sans-serif",
        2.5,
        "#070b18",
        "#818cf8",
        "#c7d2fe",
    ],
    [
        "quantum",
        "Quantum",
        "cyber",
        "zoom",
        "Outfit, sans-serif",
        2.7,
        "#030712",
        "#06b6d4",
        "#a5f3fc",
    ],
    [
        "system-error",
        "System Error",
        "cyber",
        "glitch",
        '"JetBrains Mono", monospace',
        0.9,
        "#090101",
        "#ef4444",
        "#fca5a5",
    ],

    [
        "royal",
        "Royal",
        "elegant",
        "draw",
        "Georgia, serif",
        5,
        "#0f172a",
        "#d4af37",
        "#fff7d6",
    ],
    [
        "luxury",
        "Luxury",
        "elegant",
        "focus",
        "Georgia, serif",
        6,
        "#090909",
        "#c9a227",
        "#faf3d2",
    ],
    [
        "silver",
        "Silver",
        "elegant",
        "fill",
        "Manrope, sans-serif",
        4.5,
        "#18181b",
        "#a1a1aa",
        "#f4f4f5",
    ],
    [
        "champagne",
        "Champagne",
        "elegant",
        "draw",
        "Georgia, serif",
        6,
        "#1c1917",
        "#e7c997",
        "#fff7ed",
    ],
    [
        "emerald",
        "Emerald",
        "elegant",
        "glow",
        "Georgia, serif",
        4,
        "#052e2b",
        "#10b981",
        "#d1fae5",
    ],
    [
        "ruby",
        "Ruby",
        "elegant",
        "pulse",
        "Georgia, serif",
        3,
        "#2a090f",
        "#be123c",
        "#ffe4e6",
    ],

    [
        "minimal-white",
        "Minimal White",
        "mono",
        "tracking",
        "Inter, sans-serif",
        4,
        "#ffffff",
        "#18181b",
        "#18181b",
    ],
    [
        "minimal-black",
        "Minimal Black",
        "mono",
        "focus",
        "Inter, sans-serif",
        4,
        "#09090b",
        "#fafafa",
        "#fafafa",
    ],
    [
        "graphite",
        "Graphite",
        "mono",
        "fill",
        "Manrope, sans-serif",
        4,
        "#18181b",
        "#71717a",
        "#e4e4e7",
    ],
    [
        "paper",
        "Paper",
        "mono",
        "draw",
        "Georgia, serif",
        5,
        "#f5f5f4",
        "#292524",
        "#44403c",
    ],
    [
        "carbon",
        "Carbon",
        "mono",
        "dash",
        '"JetBrains Mono", monospace',
        2.5,
        "#101010",
        "#525252",
        "#d4d4d4",
    ],

    [
        "candy",
        "Candy",
        "colorful",
        "zoom",
        "Outfit, sans-serif",
        2.2,
        "#2e1065",
        "#fb7185",
        "#fde047",
    ],
    [
        "aqua-lime",
        "Aqua Lime",
        "colorful",
        "wave",
        "Outfit, sans-serif",
        2.5,
        "#042f2e",
        "#2dd4bf",
        "#bef264",
    ],
    [
        "purple-orange",
        "Purple Orange",
        "colorful",
        "pulse",
        "Manrope, sans-serif",
        2.6,
        "#240b36",
        "#a855f7",
        "#fb923c",
    ],
    [
        "blue-yellow",
        "Blue Yellow",
        "colorful",
        "slide",
        "Impact, sans-serif",
        2,
        "#172554",
        "#3b82f6",
        "#fde047",
    ],
    [
        "mint-pink",
        "Mint Pink",
        "colorful",
        "float",
        "Outfit, sans-serif",
        3,
        "#052e2b",
        "#5eead4",
        "#f9a8d4",
    ],
    [
        "sunset",
        "Sunset",
        "colorful",
        "fill",
        "Outfit, sans-serif",
        3.5,
        "#431407",
        "#f97316",
        "#fda4af",
    ],
    [
        "ocean",
        "Ocean",
        "colorful",
        "glow",
        "Manrope, sans-serif",
        3.5,
        "#082f49",
        "#0ea5e9",
        "#67e8f9",
    ],

    [
        "soft-blue",
        "Soft Blue",
        "soft",
        "blur-in",
        "Manrope, sans-serif",
        5,
        "#eff6ff",
        "#93c5fd",
        "#1e3a8a",
    ],
    [
        "soft-pink",
        "Soft Pink",
        "soft",
        "float",
        "Manrope, sans-serif",
        5,
        "#fdf2f8",
        "#f9a8d4",
        "#831843",
    ],
    [
        "soft-green",
        "Soft Green",
        "soft",
        "focus",
        "Manrope, sans-serif",
        5,
        "#f0fdf4",
        "#86efac",
        "#14532d",
    ],
    [
        "soft-purple",
        "Soft Purple",
        "soft",
        "tracking",
        "Outfit, sans-serif",
        4.5,
        "#faf5ff",
        "#d8b4fe",
        "#581c87",
    ],
    [
        "soft-orange",
        "Soft Orange",
        "soft",
        "fill",
        "Outfit, sans-serif",
        4,
        "#fff7ed",
        "#fdba74",
        "#7c2d12",
    ],

    [
        "midnight",
        "Midnight",
        "dark",
        "stroke",
        "Inter, sans-serif",
        4,
        "#020617",
        "#475569",
        "#f8fafc",
    ],
    [
        "dark-purple",
        "Dark Purple",
        "dark",
        "glow",
        "Outfit, sans-serif",
        3,
        "#090514",
        "#7c3aed",
        "#ddd6fe",
    ],
    [
        "dark-red",
        "Dark Red",
        "dark",
        "pulse",
        "Manrope, sans-serif",
        2.5,
        "#120405",
        "#991b1b",
        "#fecaca",
    ],
    [
        "dark-blue",
        "Dark Blue",
        "dark",
        "dash",
        "Manrope, sans-serif",
        2.5,
        "#071122",
        "#1d4ed8",
        "#bfdbfe",
    ],
    [
        "dark-green",
        "Dark Green",
        "dark",
        "neon-flicker",
        '"JetBrains Mono", monospace',
        2,
        "#04100a",
        "#15803d",
        "#bbf7d0",
    ],
    [
        "obsidian",
        "Obsidian",
        "dark",
        "focus",
        "Outfit, sans-serif",
        4,
        "#050505",
        "#404040",
        "#fafafa",
    ],
];

export const animatedTextPresets: AnimatedTextPreset[] = seeds.map(
    ([
        id,
        title,
        category,
        animation,
        fontFamily,
        animationSpeed,
        backgroundColor,
        strokeColor,
        fillColor,
    ]) => ({
        id,
        title,
        category,

        config: {
            fontFamily,

            fontSize: defaults.fontSize,

            animation,

            animationSpeed,

            backgroundColor,

            strokeColor,

            fillColor,
        },
    }),
);
