import { loaderUsesChildren,type LoaderConfig } from "./loader.type";
const delays=(c:LoaderConfig)=>Array.from({length:c.count},(_,i)=>`.css-loader > span:nth-child(${i+1}) { animation-delay: -${((c.speed/c.count)*i).toFixed(2)}s; }`).join("\n");
const childBase=(c:LoaderConfig,shape="50%")=>`.css-loader{display:flex;align-items:center;justify-content:center;gap:${c.gap}px;height:${c.size}px}.css-loader>span{width:${Math.max(5,c.size/6)}px;height:${Math.max(5,c.size/6)}px;border-radius:${shape};background:${c.color};animation-duration:${c.speed}s;animation-iteration-count:infinite;animation-timing-function:ease-in-out}${delays(c)}`;
export const loaderConfigToCss=(c:LoaderConfig)=>{
 if(["dots","bouncing-dots","fading-dots","typing","chasing-dots"].includes(c.type)){const f=c.type==="dots"?"0%,100%{transform:scale(.45);opacity:.25}50%{transform:scale(1);opacity:1}":c.type==="fading-dots"?"0%,100%{opacity:.15;filter:blur(2px)}50%{opacity:1;filter:blur(0)}":c.type==="typing"?"0%,80%,100%{transform:translateY(0);opacity:.25}40%{transform:translateY(-6px);opacity:1}":c.type==="chasing-dots"?`0%{transform:rotate(0) translateX(${c.size/3}px) rotate(0)}100%{transform:rotate(360deg) translateX(${c.size/3}px) rotate(-360deg)}`:`0%,100%{transform:translateY(0);opacity:.4}50%{transform:translateY(-${c.size/3}px);opacity:1;background:${c.accentColor}}`;return `${childBase(c)}.css-loader>span{animation-name:loader-points}@keyframes loader-points{${f}}`;}
 if(["bars","wave-bars","equalizer"].includes(c.type)){const f=c.type==="equalizer"?"0%,100%{height:18%;transform:translateY(36%)}50%{height:100%;transform:translateY(0)}":c.type==="wave-bars"?"0%,100%{transform:scaleY(.25);opacity:.35}50%{transform:scaleY(1);opacity:1}":"0%,100%{height:25%;opacity:.4}50%{height:100%;opacity:1}";return `${childBase(c,`${Math.max(2,c.thickness)}px`)}.css-loader>span{width:${Math.max(3,c.thickness)}px;height:100%;transform-origin:center;background:linear-gradient(${c.color},${c.accentColor});animation-name:loader-bars}@keyframes loader-bars{${f}}`;}
 if(c.type==="grid-pulse")return `.css-loader{display:grid;grid-template-columns:repeat(3,${c.size/4}px);gap:${c.gap}px}.css-loader>span{aspect-ratio:1;border-radius:${c.thickness}px;background:${c.color};animation:grid-pulse ${c.speed}s ease-in-out infinite}${delays(c)}@keyframes grid-pulse{0%,100%{transform:scale(.35);opacity:.25}50%{transform:scale(1);opacity:1;background:${c.accentColor}}}`;
 if(c.type==="dual-ring"||c.type==="triple-ring")return `.css-loader{position:relative;width:${c.size}px;height:${c.size}px;border:${c.thickness}px solid transparent;border-top-color:${c.color};border-bottom-color:${c.accentColor};border-radius:50%;animation:loader-spin ${c.speed}s linear infinite}.css-loader::before${c.type==="triple-ring"?",.css-loader::after":""}{content:"";position:absolute;inset:${c.thickness+3}px;border:${Math.max(2,c.thickness-2)}px solid transparent;border-left-color:${c.tertiaryColor};border-right-color:${c.accentColor};border-radius:50%;animation:loader-spin ${c.speed*.65}s linear reverse infinite}${c.type==="triple-ring"?`.css-loader::after{inset:${c.thickness*2+7}px;border-top-color:${c.color};border-left-color:transparent;animation-direction:normal}`:""}@keyframes loader-spin{to{transform:rotate(1turn)}}`;
 if(c.type==="orbit"||c.type==="double-orbit")return `.css-loader{position:relative;width:${c.size}px;height:${c.size}px;border:${Math.max(1,c.thickness/2)}px solid color-mix(in srgb,${c.color} 25%,transparent);border-radius:50%;animation:loader-spin ${c.speed}s linear infinite}.css-loader::before,.css-loader::after{content:"";position:absolute;width:${c.thickness*2}px;height:${c.thickness*2}px;border-radius:50%;background:${c.color};box-shadow:0 0 ${c.thickness*3}px ${c.color}}.css-loader::before{left:50%;top:-${c.thickness}px}.css-loader::after{right:-${c.thickness}px;bottom:18%;background:${c.accentColor};${c.type==="orbit"?"display:none":""}}@keyframes loader-spin{to{transform:rotate(1turn)}}`;
 if(c.type==="pulse"||c.type==="ripple")return `.css-loader{position:relative;width:${c.size}px;height:${c.size}px;border-radius:50%;background:${c.type==="pulse"?c.color:"transparent"};border:${c.type==="ripple"?`${c.thickness}px solid ${c.color}`:"0"};animation:loader-pulse ${c.speed}s ease-out infinite}.css-loader::after{content:"";position:absolute;inset:0;border-radius:inherit;border:${c.thickness}px solid ${c.accentColor};animation:loader-pulse ${c.speed}s ease-out ${c.speed/2}s infinite}@keyframes loader-pulse{0%{transform:scale(.3);opacity:1}100%{transform:scale(1.45);opacity:0}}`;
 if(c.type==="hourglass")return `.css-loader{width:${c.size}px;height:${c.size}px;border:${c.thickness}px solid transparent;border-top-color:${c.color};border-bottom-color:${c.accentColor};border-radius:50%;animation:hourglass ${c.speed}s ease-in-out infinite}@keyframes hourglass{0%{transform:rotate(0);border-radius:50%}50%{transform:rotate(180deg);border-radius:12%}100%{transform:rotate(360deg);border-radius:50%}}`;
 if(c.type==="square-spin"||c.type==="flip-cube")return `.css-loader{width:${c.size}px;height:${c.size}px;border-radius:${c.type==="square-spin"?c.thickness:4}px;background:linear-gradient(135deg,${c.color},${c.accentColor});box-shadow:inset 0 0 0 ${c.thickness}px color-mix(in srgb,${c.tertiaryColor} 45%,transparent);animation:${c.type==="square-spin"?"square-spin":"flip-cube"} ${c.speed}s ease-in-out infinite}@keyframes square-spin{0%{transform:perspective(180px) rotateX(0) rotateY(0)}50%{transform:perspective(180px) rotateX(-180deg)}100%{transform:perspective(180px) rotateX(-180deg) rotateY(-180deg)}}@keyframes flip-cube{0%,100%{transform:rotate3d(1,1,0,0) scale(.8)}50%{transform:rotate3d(1,1,0,180deg) scale(1)}}`;
 if(c.type==="progress")return `.css-loader{width:${c.size*2}px;height:${c.thickness*2}px;overflow:hidden;border-radius:${c.thickness}px;background:color-mix(in srgb,${c.color} 20%,transparent)}.css-loader::after{content:"";display:block;width:45%;height:100%;border-radius:inherit;background:linear-gradient(90deg,${c.color},${c.accentColor},${c.tertiaryColor});animation:loader-progress ${c.speed}s ease-in-out infinite}@keyframes loader-progress{0%{transform:translateX(-110%)}100%{transform:translateX(330%)}}`;
 return `.css-loader{width:${c.size}px;height:${c.size}px;box-sizing:border-box;border:${c.thickness}px solid color-mix(in srgb,${c.color} 20%,transparent);border-top-color:${c.color};border-right-color:${c.accentColor};border-radius:50%;animation:loader-spin ${c.speed}s cubic-bezier(.55,.15,.45,.85) infinite}@keyframes loader-spin{to{transform:rotate(1turn)}}`;
};
export const loaderConfigToHtml=(c:LoaderConfig)=>`<div class="css-loader" role="status" aria-label="Loading">${loaderUsesChildren(c.type)?Array.from({length:c.count},()=>"<span></span>").join(""):""}</div>`;
